# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InSAR_TS_Toolbox
                                 A QGIS plugin
 A toolbox for InSAR time-series analysis and visualization.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-03
        copyright            : Ashwin Kumar Dhanasekaran, Kourosh Shahryarinia, and Mohammad Omidalizarandi
        email                : ashwinkumard.11@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load InSAR_TS_Toolbox class from file InSAR_TS_Toolbox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .insar_ts_toolbox import InSAR_TS_Toolbox
    return InSAR_TS_Toolbox(iface)
