# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InSAR_TS_ToolboxDialog
                                 A QGIS plugin
 A toolbox for InSAR time-series analysis and visualization.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-03
        git sha              : $Format:%H$
        author               : Ashwin Kumar Dhanasekaran M. Sc., Kourosh Shahryarinia M. Sc., Dr.-Ing. Mohammad Omidalizarandi
        Copyright (C) 2025  Ashwin Kumar Dhanasekaran, Kourosh Shahryarinia, and Mohammad Omidalizarandi
        email                : ashwinkumard.11@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'insar_ts_toolbox_dialog_base.ui'))


class InSAR_TS_ToolboxDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InSAR_TS_ToolboxDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Connect the algorithm dropdown change to function onAlgorithmChanged
        self.comboAlgorithm.currentTextChanged.connect(self.on_algorithm_changed)

        # Initialise visibility on start
        self.on_algorithm_changed(self.comboAlgorithm.currentText())

    def on_algorithm_changed(self, algorithm):
        if algorithm == 'KMeans':
            self.stackedParams.setCurrentIndex(0)  # pageKMeans
        elif algorithm == 'DBSCAN':
            self.stackedParams.setCurrentIndex(1)  # pageDBSCAN
        elif algorithm == 'DBSCAN with DTW':
            self.stackedParams.setCurrentIndex(2)
