# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InSAR_TS_Toolbox
                                 A QGIS plugin
 A toolbox for InSAR time-series analysis and visualization.
 Generated by Plugin Builder, extended with clustering, TS analysis, and Help tab.
                              -------------------
        begin                : 2025-10-03
        git sha              : $Format:%H$
        author               : Ashwin Kumar Dhanasekaran M.Sc.
        email                : ashwinkumard.11@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# stdlib
import os
import re
import shutil

# third-party (numeric/plotting)
import numpy as np
import pandas as pd
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.ticker import MaxNLocator, EngFormatter
from matplotlib import dates as mdates

# Qt
from qgis.PyQt.QtCore import Qt, pyqtSignal, QVariant, QTimer, QUrl, QProcess, QSettings
from qgis.PyQt.QtGui import QIcon, QColor, QDesktopServices
from qgis.PyQt.QtWidgets import (
    QAction, QMessageBox, QFileDialog, QPushButton, QDialog, QVBoxLayout, QHBoxLayout,
    QLabel, QCheckBox, QListWidget, QListWidgetItem, QDialogButtonBox, QComboBox,
    QSpinBox, QTextBrowser, QScrollArea, QWidget, QTabWidget, QGroupBox, QHBoxLayout, QTextBrowser, QSizePolicy, QComboBox,QSplitter, 
    QFormLayout, QFrame, QSizePolicy,QMessageBox, QCheckBox
)

# QGIS core/gui
from qgis.core import (
    QgsProject, QgsField, QgsFeature, QgsGeometry, QgsPointXY, QgsVectorLayer,
    QgsRendererCategory, QgsCategorizedSymbolRenderer, QgsSymbol, QgsWkbTypes,
    QgsFeatureRequest, QgsCoordinateTransform, QgsRectangle, QgsStatisticalSummary,
    QgsStyle, edit, QgsMessageLog, Qgis, QgsMapLayer
)
from qgis.gui import QgsMapTool, QgsRubberBand

# Local UI
from .insar_ts_toolbox_dialog import InSAR_TS_ToolboxDialog

# GitHub link
GITHUB_URL = "https://github.com/AKD11-09/insar-ts-toolbox"

# Matplotlib (Qt canvas)
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.ticker import MaxNLocator, EngFormatter
from matplotlib import dates as mdates

# Send a message to QGIS log (and stdout as fallback)
def _log(msg):
    try:
        QgsMessageLog.logMessage(str(msg), 'InSAR-TS Toolbox', Qgis.Info)
    except Exception:
        print('[InSAR-TS Toolbox]', msg)

# Rectangle map tool for area selection
class RectangleMapTool(QgsMapTool):
    rectangleSelected = pyqtSignal(QgsRectangle)
    
    def __init__(self, canvas):
        super().__init__(canvas)
        self.canvas = canvas
        self.rubber = None
        self.start = None

    def canvasPressEvent(self, e):
        self.start = self.toMapCoordinates(e.pos())
        if self.rubber:
            self.canvas.scene().removeItem(self.rubber)
        self.rubber = QgsRubberBand(self.canvas, QgsWkbTypes.PolygonGeometry)
        self.rubber.setStrokeColor(QColor(0, 0, 0))
        self.rubber.setFillColor(QColor(0, 0, 0, 0))
        self.rubber.setWidth(2)

    def canvasMoveEvent(self, e):
        if not self.start or not self.rubber:
            return
        end = self.toMapCoordinates(e.pos())
        rect = QgsRectangle(self.start, end)
        self.rubber.setToGeometry(QgsGeometry.fromRect(rect), None)

    def canvasReleaseEvent(self, e):
        if not self.start or not self.rubber:
            return
        end = self.toMapCoordinates(e.pos())
        rect = QgsRectangle(self.start, end)
        self.rectangleSelected.emit(rect)
        self.deactivate()

    def deactivate(self):
        try:
            if self.rubber:
                self.canvas.scene().removeItem(self.rubber)
        except Exception:
            pass
        self.rubber = None
        super().deactivate()

# Dialog to select layer and area option
class LayerAreaDialog(QDialog):

    def __init__(self, iface, parent=None):
        super().__init__(parent)
        self.iface = iface
        self.setWindowTitle("Data Properties – Area Selection")
        layout = QVBoxLayout(self)
        hl = QHBoxLayout()
        hl.addWidget(QLabel("Layer:"))
        self.cmbLayer = QComboBox()
        self.layers = [lyr for lyr in QgsProject.instance().mapLayers().values()
                       if isinstance(lyr, QgsVectorLayer)]
        for lyr in self.layers:
            self.cmbLayer.addItem(lyr.name())
        hl.addWidget(self.cmbLayer)
        layout.addLayout(hl)
        self.chkUseROI = QCheckBox("Limit to area (draw rectangle on map)")
        layout.addWidget(self.chkUseROI)
        btns = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        layout.addWidget(btns)
        btns.accepted.connect(self.accept)
        btns.rejected.connect(self.reject)

    def selectedLayer(self):
        if not self.layers:
            return None
        return self.layers[self.cmbLayer.currentIndex()]

# Dialog to select fields and statistics
class StatsChoiceDialog(QDialog):
    def __init__(self, layer, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Data Properties – Fields & Statistics")
        layout = QVBoxLayout(self)
        layout.addWidget(QLabel("Numeric fields:"))
        self.listFields = QListWidget()
        self.listFields.setSelectionMode(QListWidget.MultiSelection)
        for f in layer.fields():
            if f.type() in (QVariant.Int, QVariant.Double):
                it = QListWidgetItem(f.name())
                it.setSelected(True)
                self.listFields.addItem(it)
        layout.addWidget(self.listFields)

        layout.addWidget(QLabel("Statistics:"))
        self.chkMean   = QCheckBox("Mean")
        self.chkMedian = QCheckBox("Median")
        self.chkStd    = QCheckBox("Std. Dev.")
        self.chkMin    = QCheckBox("Min")
        self.chkMax    = QCheckBox("Max")
        self.chkCount  = QCheckBox("Count")
        self.chkHist   = QCheckBox("Histogram")

        for w in (self.chkMean, self.chkMedian, self.chkStd, self.chkMin, self.chkMax, self.chkCount, self.chkHist):
            layout.addWidget(w)
        for w in (self.chkMean, self.chkMedian, self.chkStd, self.chkMin, self.chkMax, self.chkCount):
            w.setChecked(True)

        hl = QHBoxLayout()
        hl.addWidget(QLabel("Histogram bins:"))
        self.spinBins = QSpinBox()
        self.spinBins.setRange(5, 100)
        self.spinBins.setValue(20)
        hl.addWidget(self.spinBins)
        layout.addLayout(hl)
        btns = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        layout.addWidget(btns)
        btns.accepted.connect(self.accept)
        btns.rejected.connect(self.reject)

    def selected_fields(self):
        return [i.text() for i in self.listFields.selectedItems()]

    def requested_stats(self):
        return dict(
            mean=self.chkMean.isChecked(),
            median=self.chkMedian.isChecked(),
            std=self.chkStd.isChecked(),
            min=self.chkMin.isChecked(),
            max=self.chkMax.isChecked(),
            count=self.chkCount.isChecked(),
            histogram=self.chkHist.isChecked(),
            bins=self.spinBins.value()
        )

# Embedded Matplotlib histogram (Qt canvas)
class HistogramCanvas(FigureCanvas):
    """Embedded Matplotlib histogram (Qt canvas) with optional PDF overlay."""
    def __init__(self, vals, field_name, bins=20, parent=None, width=4.2, height=1.8, dpi=110):
        self.fig = Figure(figsize=(width, height), dpi=dpi)
        super().__init__(self.fig)
        self.setParent(parent)

        vals = np.asarray(vals, dtype=float)
        vals = vals[np.isfinite(vals)]
        bins = int(max(5, min(bins, 50)))

        self.ax = self.fig.add_subplot(111)
        self.hist_art = self.ax.hist(vals, bins=bins, edgecolor='black', density=True)
        self.ax.set_title(field_name, fontsize=10, pad=6, fontweight='bold')
        self.ax.set_ylabel("density", fontsize=9)
        self.ax.set_xlabel(field_name, fontsize=9)
        self.ax.tick_params(labelsize=9)
        self.ax.grid(axis='y', linestyle='--', alpha=0.35)
        self._pdf_line = None
        self.ax.xaxis.set_major_locator(MaxNLocator(nbins=5, prune='both'))
        self.ax.xaxis.set_major_formatter(EngFormatter(places=0))
        self.fig.tight_layout(pad=0.8)

    def overlay_pdf(self, x, y):
        if self._pdf_line is None:
            (self._pdf_line,) = self.ax.plot(x, y, linewidth=2.0)
        else:
            self._pdf_line.set_data(x, y)
        self.ax.relim()
        self.ax.autoscale_view()
        self.fig.canvas.draw_idle()

# Embedded Matplotlib time-series (Qt canvas)
class TimeSeriesCanvas(FigureCanvas):

    def __init__(self, dates, values, title="", parent=None, width=8.0, height=3.0, dpi=110):
        self.fig = Figure(figsize=(width, height), dpi=dpi)
        super().__init__(self.fig)
        self.setParent(parent)
        
        ax = self.fig.add_subplot(211)
        ax.plot(dates, values, linestyle='-', linewidth=1.2, label='_nolegend_')
        pts = ax.scatter(dates, values, marker='o', color='red', s=10, label='PS measurements')
        ax.legend(handles=[pts], loc='upper right', framealpha=0.9, fontsize=9)
        ax.set_title(title, fontsize=11, pad=6)
        ax.set_xlabel("Year", fontsize=10)
        ax.set_ylabel("Displacement (mm)", fontsize=10)
        ax.grid(True, linestyle='--', alpha=0.35)
        ax.xaxis.set_major_locator(mdates.AutoDateLocator())
        ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(ax.xaxis.get_major_locator()))
        ax.tick_params(labelsize=9)
        
        
        # --- spectral analysis (FFT) with proper amplitude in mm ---
        # time → years from start
        t_days = np.array([(d - dates[0]).days for d in dates], dtype=float)
        t_yrs  = t_days / 365.25
        y_raw  = np.asarray(values, dtype=float)

        # detrend (linear) to reduce leakage
        try:
            p = np.polyfit(t_yrs, y_raw, 1)
            y_detr = y_raw - (p[0] * t_yrs + p[1])
        except Exception:
            y_detr = y_raw - np.nanmean(y_raw)

        # window with Hann and compensate coherent gain (≈0.5 for Hann)
        N = len(y_detr)
        if N < 4:
            dom_freqs = np.array([np.nan, np.nan, np.nan])
            dom_amps  = np.array([np.nan, np.nan, np.nan])
        else:
            w  = np.hanning(N)
            cg = w.mean() if np.isfinite(w.mean()) and w.mean() > 0 else 1.0
            y  = (y_detr - np.nanmean(y_detr)) * w

            # sampling step in years (median for quasi-irregular sampling)
            dt_days = np.median(np.diff(t_days))
            if not np.isfinite(dt_days) or dt_days <= 0:
                dt_days = 1.0
            dt_yrs = dt_days / 365.25

            # FFT → frequencies (cycles/year) and properly scaled amplitudes (mm)
            Y = np.fft.rfft(y)
            freqs_cpy = np.fft.rfftfreq(N, d=dt_yrs)      # cycles / year
            A = (2.0 / (N * cg)) * np.abs(Y)              # amplitude in mm
            if A.size > 0:
                A[0] = 0.0                                # ignore DC

            # pick 3 dominant components
            idx_sorted = np.argsort(A)[::-1]
            dom_freqs  = freqs_cpy[idx_sorted[:3]]
            dom_amps   = A[idx_sorted[:3]]

        # --- spectrum plot ---
        ax2 = self.fig.add_subplot(212)

        if N < 4 or len(freqs_cpy) == 0:
            ax2.text(0.5, 0.5, "Not enough data for spectrum",
                    ha="center", va="center", transform=ax2.transAxes)
        else:
            ax2.plot(freqs_cpy, A, linewidth=1.6)
            if A.size > 1:
                order = np.argsort(A[1:])[::-1] + 1  
                topk = order[:3]
            else:
                topk = np.array([0], dtype=int)
            markers = ["o", "s", "^"]
            for i, idx in enumerate(topk):
                fpk = float(freqs_cpy[idx])
                apk = float(A[idx])
                ax2.scatter([fpk], [apk], s=55, marker=markers[i % len(markers)],
                            label=f"{apk:.2f} mm @ {fpk:.3f} cpy", zorder=3)
            if len(topk) > 0:
                ax2.axvline(freqs_cpy[topk[0]], linestyle="--", linewidth=1.0, alpha=0.8)

        ax2.set_xlabel("Frequency (cycles/year)", fontsize=10)
        ax2.set_ylabel("Amplitude (mm)", fontsize=10)
        ax2.set_title("Amplitude Spectrum", fontsize=10, pad=4)
        ax2.grid(True, linestyle="--", alpha=0.35)
        leg = ax2.legend(loc="upper right", frameon=True, framealpha=0.9, fontsize=9)
        self.fig.tight_layout(pad=0.01, h_pad=0.01)
        self.fig.subplots_adjust(left=0.1)  



# --- Data Properties Results Dialog ---
class DataPropsResultsDialog(QDialog):

    def __init__(self, parent, title, sections):
        super().__init__(parent)
        self.setWindowTitle(title)

        try:
            import scipy.stats as _st  
            self._have_scipy = True
        except Exception:
            self._have_scipy = False

        self.cards = []  
        root = QVBoxLayout(self)
        scroll = QScrollArea(self); scroll.setWidgetResizable(True)
        root.addWidget(scroll, 1)
        host = QWidget(); scroll.setWidget(host)
        v = QVBoxLayout(host); v.setContentsMargins(6, 6, 6, 6); v.setSpacing(10)


        for idx, sec in enumerate(sections):
            name = sec.get("name", "")
            vals = np.asarray(sec.get("vals", []), dtype=float)
            vals = vals[np.isfinite(vals)]
            bins = int(sec.get("bins", 20))

            box = QGroupBox(name); box_l = QHBoxLayout(box)
            box_l.setContentsMargins(8, 8, 8, 8); box_l.setSpacing(10)

            # LEFT: stats HTML
            stats = QTextBrowser(box)
            stats.setOpenExternalLinks(False)
            stats.setStyleSheet("font-size: 11.5pt;")
            stats.setHtml(sec.get("html", ""))
            stats.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
            stats.setMinimumWidth(260); stats.setMaximumWidth(380)

            # RIGHT: controls + histogram
            right = QWidget(box); rlay = QVBoxLayout(right)
            rlay.setContentsMargins(0, 0, 0, 0)

            # Dist selector
            row = QHBoxLayout()
            row.addWidget(QLabel("Distribution:"))
            combo = QComboBox(right)


            combo.addItem("Normal")
            combo.addItem("Uniform")             # NEW
            combo.addItem("Exponential (+)")     # NEW (positive-support)
            if self._have_scipy:
                combo.addItem("Chi-square (+)")  # NEW (positive-support; needs SciPy)
                combo.addItem("Student-t")
            else:
                combo.setToolTip("SciPy not available; Chi-square and Student-t disabled")



            row.addStretch(1)
            row.addWidget(combo)
            rlay.addLayout(row)
            canvas = HistogramCanvas(vals, name, bins=bins, parent=right, width=5.8, height=1.9, dpi=110)
            canvas.setMinimumHeight(190)
            rlay.addWidget(canvas, 1)
            box_l.addWidget(stats, 0)
            box_l.addWidget(right, 1)
            v.addWidget(box)
            self.cards.append(dict(
                name=name, vals=vals, bins=bins, stats=stats, canvas=canvas, combo=combo
            ))

            # Connect callback
            combo.setProperty("card_index", idx) 
            combo.currentIndexChanged.connect(self._on_combo_changed)

            # Initial fit (Normal)
            self._apply_distribution(idx, combo.currentText())


        v.addStretch(1)
        btns = QDialogButtonBox(QDialogButtonBox.Close)
        btns.rejected.connect(self.reject)
        btns.accepted.connect(self.accept)
        root.addWidget(btns)

    # ---------- helpers ----------
    def _apply_distribution(self, i, dist_name):
        c = self.cards[i]
        vals = c["vals"]
        if vals.size < 2:
            return

        if dist_name.lower().startswith("normal"):
            # Fit Normal: mean & std (MLE)
            mu = float(np.mean(vals))
            sigma = float(np.std(vals, ddof=0))
            pdf_x, pdf_y = self._pdf_normal(vals, mu, sigma)
            stats = self._stats_from_normal(vals, mu, sigma)

        elif dist_name.lower().startswith("student") or dist_name.lower().startswith("t"):
            if not self._have_scipy:
                return
            df, loc, scale = self._fit_student_t(vals)
            pdf_x, pdf_y = self._pdf_t(vals, df, loc, scale)
            stats = self._stats_from_t(vals, df, loc, scale)

        elif dist_name.lower().startswith("uniform"):
            pdf_x, pdf_y = self._pdf_uniform(vals)
            stats = self._stats_from_sample(vals)

        elif dist_name.lower().startswith("exponential"):
            pdf_x, pdf_y = self._pdf_exponential(vals)
            stats = self._stats_from_sample(vals)

        elif dist_name.lower().startswith("chi-square"):
            pdf_x, pdf_y = self._pdf_chisquare(vals)
            stats = self._stats_from_sample(vals)

        else:
            return

        # Update left stats HTML
        html = self._stats_to_html(c["name"], stats)
        c["stats"].setHtml(html)

        # Overlay PDF on histogram
        c["canvas"].overlay_pdf(pdf_x, pdf_y)

    def _on_combo_changed(self, _i):
        combo = self.sender()
        if combo is None:
            return
        idx = combo.property("card_index")
        try:
            idx = int(idx)
        except Exception:
            return
        self._apply_distribution(idx, combo.currentText())


    def _stats_to_html(self, fname, d):
        def fmt(x):
            try: return f"{x:.6g}"
            except Exception: return str(x)
        rows = [
            ("Count", d["count"]),
            ("Mean", d["mean"]),
            ("Median", d["median"]),
            ("Std. Dev.", d["std"]),
            ("Min", d["min"]),
            ("Max", d["max"]),
            *([("df (t)", d["df"])] if "df" in d else []),
        ]
        parts = [
            "<style>table{border-collapse:collapse;} th,td{border:1px solid #ccc;padding:6px 10px;} th{background:#f5f5f5;text-align:left;}</style>",
            f"<div class='field-title' style='font-weight:600;font-size:13pt;margin:0 0 6px 0'>{fname}</div>",
            "<table><tbody>"
        ]
        for k, v in rows:
            parts.append(f"<tr><th>{k}</th><td>{fmt(v)}</td></tr>")
        parts.append("</tbody></table>")
        return "".join(parts)

    # -------- Normal --------
    def _pdf_normal(self, vals, mu, sigma):
        x = np.linspace(np.min(vals), np.max(vals), 400)
        if sigma <= 0 or not np.isfinite(sigma):  # avoid divide-by-zero
            y = np.zeros_like(x)
        else:
            y = (1.0 / (np.sqrt(2*np.pi) * sigma)) * np.exp(-0.5*((x - mu)/sigma)**2)
        return x, y

    def _stats_from_normal(self, vals, mu, sigma):
        return dict(
            count=int(vals.size),
            mean=float(mu),
            median=float(mu),     # for Normal, median==mean
            std=float(sigma),
            min=float(np.min(vals)),
            max=float(np.max(vals)),
        )

    # -------- Student-t --------
    def _fit_student_t(self, vals):
        import scipy.stats as st
        # MLE fit: returns (df, loc, scale)
        df, loc, scale = st.t.fit(vals)  # robust for heavier tails
        return float(df), float(loc), float(scale)

    def _pdf_t(self, vals, df, loc, scale):
        import scipy.stats as st
        x = np.linspace(np.min(vals), np.max(vals), 400)
        y = st.t.pdf((x - loc)/scale, df) / scale
        return x, y

    def _stats_from_t(self, vals, df, loc, scale):
        # Theoretical moments (when defined)
        # mean exists if df>1, variance exists if df>2
        mean = loc if df > 1 else np.nan
        var = (df * scale**2)/(df - 2) if df > 2 else np.nan
        std = np.sqrt(var) if np.isfinite(var) else np.nan
        median = loc  # symmetric
        return dict(
            count=int(vals.size),
            mean=float(mean),
            median=float(median),
            std=float(std) if np.isfinite(std) else np.nan,
            min=float(np.min(vals)),
            max=float(np.max(vals)),
            df=float(df),
        )
    def _stats_from_sample(self, vals):
        vals = np.asarray(vals, dtype=float)
        return dict(
            count=int(vals.size),
            mean=float(np.mean(vals)),
            median=float(np.median(vals)),
            std=float(np.std(vals, ddof=0)),
            min=float(np.min(vals)),
            max=float(np.max(vals)),
        )

    def _pdf_uniform(self, vals):
        # U(a,b) with a=min, b=max
        a = float(np.min(vals)); b = float(np.max(vals))
        if not np.isfinite(a) or not np.isfinite(b) or b <= a:
            x = np.linspace(a, a + 1.0, 400); y = np.zeros_like(x)
            return x, y
        x = np.linspace(a, b, 400)
        y = np.full_like(x, 1.0 / (b - a))
        return x, y

    def _pdf_exponential(self, vals):
        v = np.asarray(vals, dtype=float)
        shift = 0.0
        vmin = float(np.min(v))
        if vmin <= 0:
            shift = -vmin + np.finfo(float).eps
            v = v + shift

        try:
            import scipy.stats as st
            params = st.expon.fit(v, floc=0)      
            scale = float(params[-1])
        except Exception:
            m = float(np.mean(v))
            scale = m if (np.isfinite(m) and m > 0) else 1.0

        x_pos = np.linspace(0, np.max(v), 400)
        y_pos = (1.0 / scale) * np.exp(-x_pos / scale)
        x = x_pos - shift
        return x, y_pos

    def _pdf_chisquare(self, vals):
        if not self._have_scipy:
            x = np.linspace(np.min(vals), np.max(vals), 400)
            return x, np.zeros_like(x)
        import scipy.stats as st
        v = np.asarray(vals, dtype=float)
        shift = 0.0
        vmin = float(np.min(v))
        if vmin <= 0:
            shift = -vmin + np.finfo(float).eps
            v = v + shift
        df, loc, scale = st.chi2.fit(v, floc=0)   # fix loc=0
        x_pos = np.linspace(0, np.max(v), 400)
        y_pos = st.chi2.pdf(x_pos, df, loc=0, scale=scale)
        x = x_pos - shift
        return x, y_pos



# ----------------Functions for utilities ----------------


def ensure_cluster_field(layer) -> int:
    idx = layer.fields().indexFromName('cluster_id')
    if idx != -1:
        return idx

    fld = QgsField('cluster_id', QVariant.Int)   # modern ctor
    fld.setTypeName('Integer')                   # optional, helps some providers
    fld.setLength(10)
    fld.setPrecision(0)

    with edit(layer):
        ok = layer.dataProvider().addAttributes([fld])
        if not ok:
            raise RuntimeError("Failed to add 'cluster_id' field.")
        layer.updateFields()

    return layer.fields().indexFromName('cluster_id')


# ---------------- main plugin ----------------
from .insar_ts_toolbox_dialog import InSAR_TS_ToolboxDialog



# Time-series point picker tool
class TSPointPickTool(QgsMapTool):
 
    picked = pyqtSignal(QgsFeature)

    def __init__(self, canvas, layer, iface=None, pixel_tolerance=8):
        super().__init__(canvas)
        self.canvas = canvas
        self.layer = layer
        self.iface = iface
        self.pixel_tolerance = int(max(2, pixel_tolerance))
        self.setCursor(Qt.CrossCursor)

    def canvasReleaseEvent(self, e):
        pt = self.toMapCoordinates(e.pos())
        tol_mu = self.pixel_tolerance * self.canvas.mapUnitsPerPixel()
        rect = QgsRectangle(pt.x() - tol_mu, pt.y() - tol_mu, pt.x() + tol_mu, pt.y() + tol_mu)
        req = QgsFeatureRequest().setFilterRect(rect)
        feats = list(self.layer.getFeatures(req))

        if not feats:
            try:
                if self.iface is not None:
                    self.iface.messageBar().pushMessage(
                        "TS Analysis",
                        "No feature under cursor (try zooming in).",
                        level=Qgis.Info,
                        duration=2
                    )
                else:
                    QgsMessageLog.logMessage("No feature under cursor (try zooming in).", "TS Analysis", Qgis.Info)
            except Exception:
                QgsMessageLog.logMessage("No feature under cursor (try zooming in).", "TS Analysis", Qgis.Info)
            return

        # pick the nearest feature center to the click
        click_geom = QgsGeometry.fromPointXY(QgsPointXY(pt))
        def _dist(ft):
            try:
                return ft.geometry().closestSegmentWithContext(pt)[0]
            except Exception:
                return ft.geometry().distance(click_geom)

        picked_ft = min(feats, key=_dist)
        self.picked.emit(picked_ft)



# ---------------- main plugin ----------------

# Main plugin class for QGIS InSAR-TS Toolbox
class InSAR_TS_Toolbox:

    def __init__(self, iface):
        self.iface = iface
        self.dlg = None
        self._rectTool = None
        self._prevTool = None
        self._tsPickTool = None

    # ---------------- GUI ----------------
    def _ensure_dialog(self):
        if self.dlg is None:
            self.dlg = InSAR_TS_ToolboxDialog()


            self.dlg.resize(1000, 700)
            self.dlg.setWindowTitle("InSAR-TS Toolbox")
            btn_cluster = getattr(self.dlg, 'btnRunCluster', None) or getattr(self.dlg, 'btnRun', None)
            if btn_cluster:
                try: btn_cluster.clicked.disconnect()
                except Exception: pass
                btn_cluster.clicked.connect(self.run_clustering)

            btn_dp = getattr(self.dlg, 'btnRunDataProps', None)
            if btn_dp:
                try: btn_dp.clicked.disconnect()
                except Exception: pass
                btn_dp.clicked.connect(self.on_data_properties)

            self.dlg.comboAlgorithm.currentTextChanged.connect(self.on_algorithm_changed)
            self.dlg.stackedParams.currentChanged.connect(self._on_params_page_changed)

            # Inject TS Analysis tab entirely in code
            self._inject_ts_tab()
            self._inject_help_tab()

        return self.dlg

    # --- TS Analysis tab (created in code) ---
    def _inject_ts_tab(self):

        dlg = self.dlg
        tabw = dlg.findChild(QTabWidget)
        if tabw is None:
            tabw = QTabWidget(dlg)
            content = QWidget()
            lay = QVBoxLayout(content)
            while dlg.layout().count():
                item = dlg.layout().takeAt(0)
                w = item.widget()
                if w:
                    lay.addWidget(w)
            tabw.addTab(content, "Main")
            dlg.layout().addWidget(tabw)

        # --- Tab ---
        tab = QWidget(dlg)
        root = QVBoxLayout(tab)

        # Top row: pick button + info
        top = QHBoxLayout()
        self.btnPickTS = QPushButton("Pick a point on map", tab)
        self.lblTSInfo = QLabel("No point selected.", tab)
        self.lblTSInfo.setStyleSheet("color:#666;")
        top.addWidget(self.btnPickTS, 0)
        top.addWidget(self.lblTSInfo, 1)
        root.addLayout(top)

        # === Splitter (plot left | attributes right) ===
        splitter = QSplitter(Qt.Horizontal, tab)

        # Left: plot container
        left = QWidget(splitter)
        left.setObjectName("frameTSPlot")
        left.setLayout(QVBoxLayout())
        left.layout().setContentsMargins(0, 0, 0, 0)
        self.frameTSPlot = left
        left.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        # Right: attributes (scrollable)
        right = QWidget(splitter)
        right_v = QVBoxLayout(right)
        right_v.setContentsMargins(6, 6, 6, 6)

        hdr = QLabel("Attributes")
        hdr.setStyleSheet("font-weight:600; margin:2px 0 8px 0;")
        right_v.addWidget(hdr, 0)

        self.featuresScroll = QScrollArea(right)
        self.featuresScroll.setWidgetResizable(True)
        self.featuresHost = QWidget()
        self.featuresForm = QFormLayout(self.featuresHost)
        self.featuresForm.setLabelAlignment(Qt.AlignLeft)
        self.featuresForm.setFormAlignment(Qt.AlignTop)
        self.featuresScroll.setWidget(self.featuresHost)
        self.featuresScroll.setFrameShape(QFrame.StyledPanel)
        right_v.addWidget(self.featuresScroll, 1)

        splitter.addWidget(left)
        splitter.addWidget(right)

        splitter.setStretchFactor(0, 3)   # plots
        splitter.setStretchFactor(1, 1)   # attributes
        QTimer.singleShot(0, lambda: splitter.setSizes([700, 300]))
        root.addWidget(splitter, 1)
        tabw.addTab(tab, "TS Analysis")

        try:
            self.btnPickTS.clicked.disconnect()
        except Exception:
            pass
        self.btnPickTS.clicked.connect(self.start_ts_pick)

    def _inject_help_tab(self):

        dlg = self.dlg
        tabw = dlg.findChild(QTabWidget)
        if tabw is None:
            return 

        tab = QWidget(dlg)
        root = QVBoxLayout(tab)
        root.setContentsMargins(8, 8, 8, 8)

        helpBox = QTextBrowser(tab)
        helpBox.setOpenExternalLinks(False)
        helpBox.setOpenLinks(False)
        helpBox.anchorClicked.connect(self._on_help_anchor_clicked)
        helpBox.setStyleSheet("font-size: 11pt; font-family: Segoe UI, Arial, sans-serif;")
        helpBox.setReadOnly(True)

        help_html = f"""
        <style>
        h2{{margin:0 0 12px 0; font-size: 14pt;}}
        h3{{margin:14px 0 6px 0; font-size: 12pt;}}
        ul{{margin:6px 0 10px 22px}}
        li{{margin-bottom:6px; line-height:1.4;}}
        code{{background:#f2f2f2;padding:1px 4px;border-radius:3px}}
        </style>

        <h2>InSAR-TS Toolbox </h2>

        <h3>Overview of Tabs</h3>

        <h4>Clustering</h4>
        <p>Select numeric fields from a point layer and run clustering with
        <b>KMeans</b> or <b>DBSCAN</b>. Results are written to a <code>cluster_id</code>
        field and visualized with automatic color symbology (noise is shown in grey).</p>

        <h4>Data Properties</h4>
        <p>Compute descriptive statistics (<i>mean, median, std, min, max, count</i>) for
        selected fields, either across the whole layer or within a drawn rectangle (ROI).
        Inline histograms are provided, with optional distribution fits
        (Normal, Student-t, Uniform, Exponential, Chi-square).</p>

        <h4>TS Analysis</h4>
        <p>Click on a point feature in a time-series dataset to display its displacement
        time series and corresponding amplitude spectrum. The three strongest spectral peaks
        are automatically highlighted and reported in the legend.</p>

        <h4>Attributes</h4>
        <p>The right-hand panel in TS Analysis lists all non-time-series attributes for the
        selected feature. The information line above shows the layer name, feature ID, and
        the number of epochs available.</p>

         <h3>TS Analysis tips</h3>
            <ul>
            <li>Time is converted to years; detrending + Hann window reduce spectral leakage.</li>
            <li>For irregular sampling, interpret high-frequency peaks cautiously.</li>
            <li>Resize panels with the splitter: plots (left) and attributes (right).</li>
            </ul>

            <h3>Troubleshooting</h3>
            <ul>
            <li><b>No feature under cursor:</b> zoom in and try again (picker uses a small pixel tolerance).</li>
            <li><b>No time-series fields found:</b> ensure fields are named like <code>YYYYMMDD</code> and contain numeric values.</li>
            <li><b>Empty stats:</b> make sure numeric fields were selected and ROI contains features.</li>
            </ul>
            
        <h3>More info</h3>
        <p>Docs &amp; source on GitHub:
        <a href="{GITHUB_URL}">{GITHUB_URL}</a></p>
        """

        helpBox.setHtml(help_html)
        root.addWidget(helpBox, 1)
        tabw.addTab(tab, "Help")



    def _on_help_anchor_clicked(self, url: QUrl):
        try:
            self._open_url_external(url.toString())
        except Exception:
            # fallback to default handler
            QDesktopServices.openUrl(url)

    def _open_url_external(self, url_str: str):

        chrome_path = None
        if os.name == "nt":  # Windows
            # Try PATH first
            chrome_path = shutil.which("chrome") or shutil.which("chrome.exe")
            # Common install locations
            if not chrome_path:
                candidates = [
                    os.path.join(os.environ.get("PROGRAMFILES", ""), "Google", "Chrome", "Application", "chrome.exe"),
                    os.path.join(os.environ.get("PROGRAMFILES(X86)", ""), "Google", "Chrome", "Application", "chrome.exe"),
                    os.path.join(os.environ.get("LOCALAPPDATA", ""), "Google", "Chrome", "Application", "chrome.exe"),
                ]
                chrome_path = next((p for p in candidates if p and os.path.exists(p)), None)

        if chrome_path and os.path.exists(chrome_path):
            # Launch Chrome detached so QGIS isn't blocked
            QProcess.startDetached(chrome_path, [url_str])
            return

        # Non-Windows or Chrome not found → open with default browser
        QDesktopServices.openUrl(QUrl(url_str))


    def _restore_canvas_tool(self, force_pan=False):
        try:
            canvas = self.iface.mapCanvas()
            tool = getattr(self, "_rectTool", None)
            prev = getattr(self, "_prevTool", None)

            if tool is not None:
                try:
                    if canvas.mapTool() is tool:
                        canvas.unsetMapTool(tool)
                except Exception:
                    pass

            if prev is not None and not force_pan:
                try:
                    canvas.setMapTool(prev)
                except Exception:
                    force_pan = True

            if force_pan or prev is None:
                try:
                    self.iface.actionPan().trigger()
                except Exception:
                    pass
        finally:
            self._rectTool = None
            self._prevTool = None

    def initGui(self):
        icon = QIcon(os.path.join(os.path.dirname(__file__), "icon.png"))
        self.action = QAction(icon, "InSAR-TS Toolbox", self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addToolBarIcon(self.action)
        self.iface.addPluginToMenu("InSAR-TS Toolbox", self.action)

    def unload(self):
        self.iface.removePluginMenu("InSAR-TS Toolbox", self.action)
        self.iface.removeToolBarIcon(self.action)

    def run(self):
        self._ensure_dialog()
        self.populate_feature_combo()
        self.on_algorithm_changed(self.dlg.comboAlgorithm.currentText())
        self.dlg.show()

    # ---------------- Dialog setup ----------------
    def populate_feature_combo(self):
        layer = self.iface.activeLayer()
        if not layer or not layer.type() == QgsMapLayer.VectorLayer:
            return

        numeric = [f.name() for f in layer.fields() if f.type() in (QVariant.Int, QVariant.Double)]
        lst = self.dlg.listFeatures
        lst.clear()
        for name in numeric:
            item = QListWidgetItem(name)
            item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
            item.setCheckState(Qt.Unchecked)
            lst.addItem(item)


    def on_algorithm_changed(self, name: str):
        name_l = (name or "").strip().lower()
        mapping = {'kmeans': 'pageKMeans', 'dbscan': 'pageDBSCAN'}
        target = mapping.get(name_l)
        if target:
            for i in range(self.dlg.stackedParams.count()):
                if self.dlg.stackedParams.widget(i).objectName() == target:
                    self.dlg.stackedParams.setCurrentIndex(i)
                    break

    def _on_params_page_changed(self, index):
        pass

    # -------- clustering --------
    def _require_sklearn(self):
        try:
            from sklearn.cluster import KMeans, DBSCAN
            from sklearn.preprocessing import StandardScaler
            return KMeans, DBSCAN, StandardScaler
        except Exception as e:
            QMessageBox.critical(self.iface.mainWindow(), "Missing dependency",
                                 f"scikit-learn is required.\n\n{e}")
            raise

    def run_clustering(self):
        layer = self.iface.activeLayer()
        if not layer:
            QMessageBox.critical(self.iface.mainWindow(), "Error", "No active layer selected.")
            return
        if layer.geometryType() != QgsWkbTypes.PointGeometry:
            QMessageBox.critical(self.iface.mainWindow(), "Error", "Selected layer is not a point layer.")
            return
        if layer.providerType() == 'delimitedtext':
            QMessageBox.information(self.iface.mainWindow(), "CSV Layer", "CSV detected. Copying to memory layer.")
            mem = QgsVectorLayer(f"Point?crs={layer.crs().authid()}", "Editable Copy", "memory")
            mem.dataProvider().addAttributes(layer.fields()); mem.updateFields()
            mem.dataProvider().addFeatures(list(layer.getFeatures()))
            QgsProject.instance().addMapLayer(mem, addToLegend=True)
            self.iface.setActiveLayer(mem)
            layer = mem

        algo = (self.dlg.comboAlgorithm.currentText() or "").strip().lower()

        selected = [self.dlg.listFeatures.item(i).text()
                    for i in range(self.dlg.listFeatures.count())
                    if self.dlg.listFeatures.item(i).checkState() == Qt.Checked]
        if not selected:
            QMessageBox.warning(self.iface.mainWindow(), "No Features Selected", "Select at least one field.")
            return

        params = {}
        if algo == 'kmeans':
            params['algo'] = 'KMeans'
            params['n_clusters'] = self.dlg.spinKMeansClusters.value()
        elif algo == 'dbscan':
            self.dlg.spinDBSCANeps.interpretText()
            params['algo'] = 'DBSCAN'
            params['eps'] = self.dlg.spinDBSCANeps.value()
            params['min_samples'] = self.dlg.spinDBSCANminPts.value()
        else:
            QMessageBox.critical(self.iface.mainWindow(), "Error", f"Unknown algorithm: {algo}")
            return

        try:
            self.perform_clustering(layer, params, selected)
            idx = layer.fields().indexFromName("cluster_id")
            vals = set(layer.dataProvider().uniqueValues(idx))
            n = len({v for v in vals if v != -1})
            QMessageBox.information(self.iface.mainWindow(), "Clustering Complete",
                                    f"{params['algo']} finished with {n} clusters.")
            self.symbolize_clusters(layer)
        except Exception as e:
            QMessageBox.critical(self.iface.mainWindow(), "Clustering Error", repr(e))

    def perform_clustering(self, layer, params, selected_fields):
        KMeans, DBSCAN, StandardScaler = self._require_sklearn()
        feats = list(layer.getFeatures())

        idxs = [layer.fields().indexFromName(f) for f in selected_fields]
        rows = []
        for ft in feats:
            row = []
            for idx in idxs:
                v = ft[idx]
                try:
                    row.append(float(v))
                except Exception:
                    row.append(np.nan)
            rows.append(row)

        X = np.array(rows, dtype=float)
        X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)
        X = StandardScaler(with_mean=True, with_std=True).fit_transform(X)

        if params['algo'] == 'KMeans':
            model = KMeans(n_clusters=int(params['n_clusters']), n_init=10, random_state=0)
        else:
            model = DBSCAN(eps=float(params['eps']), min_samples=int(params['min_samples']))
        labels = model.fit_predict(X)

        idx = ensure_cluster_field(layer)

        must_commit = False
        if not layer.isEditable():
            layer.startEditing()
            must_commit = True

        try:
            for ft, lab in zip(feats, labels):
                layer.changeAttributeValue(ft.id(), idx, int(lab))
            if must_commit:
                if not layer.commitChanges():
                    layer.rollBack()
                    raise RuntimeError("Commit failed: " + "; ".join(layer.commitErrors()))
        except Exception:
            if must_commit:
                layer.rollBack()
            raise

    def symbolize_clusters(self, layer):
        idx = layer.fields().indexFromName("cluster_id")
        vals = sorted(set(layer.dataProvider().uniqueValues(idx)))
        cats = []
        style = QgsStyle().defaultStyle()
        ramp = style.colorRamp('Spectral') or style.colorRamp('Random colors')

        nvals = max(1, len(vals))
        for i, v in enumerate(vals):
            sym = QgsSymbol.defaultSymbol(layer.geometryType())
            if v == -1:
                sym.setColor(QColor(150, 150, 150))  # noise as gray
            elif ramp and nvals > 1:
                t = 0.0 if nvals == 1 else (i / float(nvals - 1))
                sym.setColor(ramp.color(t))
            label = "Noise (-1)" if v == -1 else f"Cluster {int(v)}"
            cats.append(QgsRendererCategory(v, sym, label))
        layer.setRenderer(QgsCategorizedSymbolRenderer("cluster_id", cats))
        layer.triggerRepaint()

    def _render_feature_attributes(self, layer, feature, title_prefix="Attributes"):

        # Clear previous rows
        if hasattr(self, "featuresForm") and self.featuresForm:
            while self.featuresForm.count():
                item = self.featuresForm.takeAt(0)
                w = item.widget()
                if w:
                    w.deleteLater()

        if not hasattr(self, "featuresForm") or self.featuresForm is None:
            return  
        
        # Build a mask for time-series fields
        ts_name_re = re.compile(r'^\d{6,8}$')   # e.g., 20190106 / 2019...

        # Optional header row
        hdr = QLabel(f"{title_prefix} for ID #{feature.id()}")
        hdr.setStyleSheet("font-weight: 600; margin: 6px 0;")
        self.featuresForm.addRow(hdr, QLabel(""))

        # Iterate attributes
        attrs = feature.attributes()
        fields = layer.fields()

   
        for idx, fld in enumerate(fields):
            name = fld.name()
            if ts_name_re.match(name): 
                continue
    
            if name.lower() in {"x", "y"} and layer.geometryType() != QgsWkbTypes.PointGeometry:
                pass  

            val = attrs[idx]
            if val is None:
                sval = "—"
            else:
                try:
                    if isinstance(val, (int, np.integer)):
                        sval = f"{int(val)}"
                    elif isinstance(val, (float, np.floating)):
                        sval = f"{float(val):.3f}"
                    else:
                        sval = str(val)
                except Exception:
                    sval = str(val)

            key_lbl = QLabel(name + ":")
            val_lbl = QLabel(sval)
            val_lbl.setTextInteractionFlags(Qt.TextSelectableByMouse)
            self.featuresForm.addRow(key_lbl, val_lbl)

        # -------- TS Analysis (pick & plot) --------
    def start_ts_pick(self):
        layer = self.iface.activeLayer()
        if self._tsPickTool: 
            self._stop_ts_pick()
            return

        if not layer or layer.geometryType() != QgsWkbTypes.PointGeometry:
            QMessageBox.warning(self.iface.mainWindow(), "TS Analysis",
                                "Please select a point layer as active.")
            return

        canvas = self.iface.mapCanvas()
        self._prevTool = canvas.mapTool()
        self._tsPickTool = TSPointPickTool(self.iface.mapCanvas(), layer, iface=self.iface, pixel_tolerance=8)

        self._tsPickTool.picked.connect(lambda f: self._on_ts_point_picked(layer, f))
        canvas.setMapTool(self._tsPickTool)

        if hasattr(self, 'lblTSInfo') and self.lblTSInfo:
            self.lblTSInfo.setText("Picking… click a point feature on the map.")
        if hasattr(self, 'btnPickTS') and self.btnPickTS:
            self.btnPickTS.setText("Stop picking")

    def _stop_ts_pick(self):

        try:
            canvas = self.iface.mapCanvas()
            if getattr(self, "_tsPickTool", None) and canvas.mapTool() is self._tsPickTool:
                canvas.unsetMapTool(self._tsPickTool)
        except Exception:
            pass
        finally:
            self._tsPickTool = None
            if getattr(self, "_prevTool", None):
                try:
                    self.iface.mapCanvas().setMapTool(self._prevTool)
                except Exception:
                    pass
            self._prevTool = None

            if hasattr(self, 'lblTSInfo') and self.lblTSInfo:
                self.lblTSInfo.setText("Picking stopped.")
            if hasattr(self, 'btnPickTS') and self.btnPickTS:
                self.btnPickTS.setText("Pick a point on map")

    def _restore_tool_after_ts(self):
        try:
            canvas = self.iface.mapCanvas()
            if getattr(self, "_tsPickTool", None) and canvas.mapTool() is self._tsPickTool:
                canvas.unsetMapTool(self._tsPickTool)
        except Exception:
            pass
        finally:
            self._tsPickTool = None
            if getattr(self, "_prevTool", None):
                try:
                    self.iface.mapCanvas().setMapTool(self._prevTool)
                except Exception:
                    pass
            self._prevTool = None

    def _on_ts_point_picked(self, layer, feature):

        ts_fields = []
        for fld in layer.fields():
            name = fld.name()
            if re.match(r'^\d+', name):
                ts_fields.append(name)

        if not ts_fields:
            QMessageBox.information(self.iface.mainWindow(), "TS Analysis",
                                    "No time-series fields found (fields starting with a date).")
            return

        dates = pd.to_datetime(ts_fields, format='%Y%m%d', errors='coerce')
        keep = ~pd.isna(dates)
        ts_pairs = [(d, n) for d, n, k in zip(dates, ts_fields, keep) if k]
        if not ts_pairs:
            QMessageBox.information(self.iface.mainWindow(), "TS Analysis",
                                    "Fields looked numeric but didn’t parse as YYYYMMDD.")
            return
        ts_pairs.sort(key=lambda x: x[0])

        xs, ys = [], []
        for d, name in ts_pairs:
            try:
                v = feature[name]
            except KeyError:
                continue
            if v is None:
                continue
            try:
                v = float(v)
            except Exception:
                continue
            xs.append(d)
            ys.append(v)

        if len(xs) == 0:
            QMessageBox.information(self.iface.mainWindow(), "TS Analysis",
                                    "Selected feature has no numeric values in the time-series fields.")
            return

        container = getattr(self, 'frameTSPlot', None)
        if container is None:
            QMessageBox.warning(self.iface.mainWindow(), "TS Analysis",
                                "Plot container not found.")
            return

        for c in container.findChildren(QWidget):
            c.setParent(None)
            c.deleteLater()

        canvas = TimeSeriesCanvas(xs, ys, title=f"Time series for ID #{feature.id()} – Displacement")
        container.layout().addWidget(canvas)

        if hasattr(self, 'lblTSInfo') and self.lblTSInfo:
            lyr_name = layer.name() if layer is not None else "—"
            self.lblTSInfo.setText(
                f"Layer: {lyr_name}  •  Feature ID: {feature.id()}  •  {len(xs)} epochs"
            )

        self.dlg.setWindowModality(Qt.NonModal)
        self.dlg.setWindowState(self.dlg.windowState() & ~Qt.WindowMinimized)
        self._render_feature_attributes(layer, feature, title_prefix="Attributes")

        self.dlg.show()
        self.dlg.raise_()
        self.dlg.activateWindow()

    

    def _data_props_show_intro(self) -> bool:

        s = QSettings()
        key = "insar_ts_toolbox/data_props_intro_suppressed"
        if s.value(key, type=bool):
            return True

        mb = QMessageBox(self.iface.mainWindow())
        mb.setIcon(QMessageBox.Information)
        mb.setWindowTitle("Data Properties – How it works")
        mb.setText(
            "This tool computes summary statistics and inline histograms for a chosen layer or ROI."
        )
        mb.setInformativeText(
            "Steps:\n"
            "1) Pick a vector layer (points/polygons) to analyze.\n"
            "2) (Optional) Limit to a map rectangle (ROI).\n"
            "3) Choose numeric fields and which stats to compute.\n\n"
            "Press OK to continue."
        )
        cb = QCheckBox("Don’t show this again")
        mb.setCheckBox(cb)
        mb.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        mb.setDefaultButton(QMessageBox.Ok)

        res = mb.exec_()
        if cb.isChecked():
            s.setValue(key, True)

        return res == QMessageBox.Ok


   
    def on_data_properties(self):

        if not self._data_props_show_intro():
            return
        parent = self._ensure_dialog()

        d = LayerAreaDialog(self.iface, parent)
        if not d.exec_():
            return
        layer = d.selectedLayer()
        if layer is None:
            QMessageBox.warning(self.iface.mainWindow(), "Data Properties", "No vector layer selected.")
            return
        roi_needed = d.chkUseROI.isChecked()

        def proceed_with_rect(rect):

            sd = StatsChoiceDialog(layer, parent)
            if not sd.exec_():
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                return

            fields = sd.selected_fields()
            if not fields:
                QMessageBox.information(self.iface.mainWindow(), "Data Properties", "No numeric fields selected.")
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                return
            opts = sd.requested_stats()

            # ROI-aware request
            req = QgsFeatureRequest()
            if rect is not None and layer.geometryType() != QgsWkbTypes.NullGeometry:
                canvas_crs = self.iface.mapCanvas().mapSettings().destinationCrs()
                if layer.crs() != canvas_crs:
                    xform = QgsCoordinateTransform(canvas_crs, layer.crs(), QgsProject.instance())
                    rect = xform.transform(rect)
                req.setFilterRect(rect)

            attr_idx = [layer.fields().indexFromName(f) for f in fields if layer.fields().indexFromName(f) != -1]

            if rect is None and layer.selectedFeatureIds():
                req_sel = QgsFeatureRequest(layer.selectedFeatureIds())
                if attr_idx:
                    req_sel.setSubsetOfAttributes(attr_idx)
                req_sel.setFlags(QgsFeatureRequest.NoGeometry)
                feats = list(layer.getFeatures(req_sel))
            else:
                if attr_idx:
                    req.setSubsetOfAttributes(attr_idx)
                req.setFlags(QgsFeatureRequest.NoGeometry)
                feats = list(layer.getFeatures(req))

            if not feats:
                QMessageBox.information(self.iface.mainWindow(), "Data Properties", "No features in the selected area.")
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                return

            # Compute stats and prep plot data
            stats_per_field = []
            plot_data = []   

            for fname in fields:
                idx = layer.fields().indexFromName(fname)
                if idx == -1:
                    continue

                vals = []
                for ft in feats:
                    v = ft[idx]
                    if v is None:
                        continue
                    try:
                        vals.append(float(v))
                    except Exception:
                        pass
                if not vals:
                    continue

                ss = QgsStatisticalSummary()
                ss.calculate(vals)

                stats_per_field.append(dict(
                    name=fname,
                    count=len(vals),
                    mean=ss.statistic(QgsStatisticalSummary.Mean),
                    median=ss.statistic(QgsStatisticalSummary.Median),
                    std=ss.statistic(QgsStatisticalSummary.StDev),
                    min=ss.statistic(QgsStatisticalSummary.Min),
                    max=ss.statistic(QgsStatisticalSummary.Max),
                ))

                if opts["histogram"]:
                    plot_data.append((fname, vals, int(opts["bins"])))

            if not stats_per_field and not plot_data:
                QMessageBox.information(self.iface.mainWindow(), "Data Properties", "No numeric results to show.")
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                return


            def fmt(x):
                try:
                    return f"{x:.6g}"
                except Exception:
                    return str(x)

            order  = ["count", "mean", "median", "std", "min", "max"]
            labels = {"count": "Count", "mean": "Mean", "median": "Median",
                    "std": "Std. Dev.", "min": "Min", "max": "Max"}
            vals_map = {}
            for fname, vals, bins_used in plot_data:
                vals_map[fname] = (vals, bins_used)

            sections = []
            for s in stats_per_field:
                fname = s["name"]
                html = [
                    "<style>table{border-collapse:collapse;} th,td{border:1px solid #ccc;padding:6px 10px;} th{background:#f5f5f5;text-align:left;}</style>",
                    f"<div class='field-title' style='font-weight:600;font-size:13pt;margin:0 0 6px 0'>{fname}</div>",
                    "<table><tbody>"
                ]
                for k in order:
                    html.append(f"<tr><th>{labels[k]}</th><td>{fmt(s[k])}</td></tr>")
                html.append("</tbody></table>")
                html = "".join(html)

                vals, bins_used = vals_map.get(fname, ([], int(opts["bins"])))
                sections.append({"name": fname, "html": html, "vals": vals, "bins": bins_used})

            if not sections:
                QMessageBox.information(self.iface.mainWindow(), "Data Properties", "No numeric results to show.")
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                return

            dlg2 = DataPropsResultsDialog(parent, "Data Properties (Summary)", sections)
            dlg2.resize(1100, 700)
            dlg2.exec_()

            QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))

        if roi_needed:
            canvas = self.iface.mapCanvas()
            self._rectTool = RectangleMapTool(canvas)
            self._prevTool = canvas.mapTool()

            def _finish(rect):
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                proceed_with_rect(rect)

            self._rectTool.rectangleSelected.connect(_finish)
            canvas.setMapTool(self._rectTool)
            self.iface.messageBar().pushInfo("Data Properties", "Draw a rectangle to select the area.")
        else:
            proceed_with_rect(None)