# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InSAR_TS_Toolbox
                                 A QGIS plugin
 A toolbox for InSAR time-series analysis and visualization.
 Generated by Plugin Builder, extended with clustering, TS analysis, and Help tab.
                              -------------------
        begin                : 2025-10-03
        git sha              : $Format:%H$
        author               : Ashwin Kumar Dhanasekaran M. Sc., Kourosh Shahryarinia M. Sc., Dr.-Ing. Mohammad Omidalizarandi
        Copyright (C) 2025  Ashwin Kumar Dhanasekaran, Kourosh Shahryarinia, and Mohammad Omidalizarandi
        email                : ashwinkumard.11@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# stdlib
import os
import re
import shutil

# third-party (numeric/plotting)
import numpy as np
import pandas as pd
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.ticker import MaxNLocator, EngFormatter
from matplotlib import dates as mdates

# Qt
from qgis.PyQt.QtCore import Qt, pyqtSignal, QVariant, QTimer, QUrl, QProcess, QSettings
from qgis.PyQt.QtGui import QIcon, QColor, QDesktopServices
from qgis.PyQt.QtWidgets import (
    QAction, QMessageBox, QFileDialog, QPushButton, QDialog, QVBoxLayout, QHBoxLayout,
    QLabel, QCheckBox, QListWidget, QListWidgetItem, QDialogButtonBox, QComboBox,
    QSpinBox, QTextBrowser, QScrollArea, QWidget, QTabWidget, QGroupBox, QHBoxLayout, QTextBrowser, QSizePolicy, QComboBox,QSplitter, 
    QFormLayout, QFrame, QSizePolicy,QMessageBox, QCheckBox
)

# QGIS core/gui
from qgis.core import (
    QgsProject, QgsField, QgsFeature, QgsGeometry, QgsPointXY, QgsVectorLayer,
    QgsRendererCategory, QgsCategorizedSymbolRenderer, QgsSymbol, QgsWkbTypes,
    QgsFeatureRequest, QgsCoordinateTransform, QgsRectangle, QgsStatisticalSummary,
    QgsStyle, edit, QgsMessageLog, Qgis, QgsMapLayer
)
from qgis.gui import QgsMapTool, QgsRubberBand

# Local UI
from .insar_ts_toolbox_dialog import InSAR_TS_ToolboxDialog

# GitHub link
GITHUB_URL = "https://github.com/AKD11-09/insar-ts-toolbox"


def _plugin_version():
    """Read the version from metadata.txt so it is declared in exactly one place."""
    try:
        import configparser
        cfg = configparser.ConfigParser()
        with open(os.path.join(os.path.dirname(__file__), 'metadata.txt'),
                  encoding='utf-8') as fh:
            cfg.read_file(fh)
        return cfg.get('general', 'version')
    except Exception:
        return 'unknown'


PLUGIN_VERSION = _plugin_version()

# Matplotlib (Qt canvas)
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.ticker import MaxNLocator, EngFormatter
from matplotlib import dates as mdates

# Send a message to QGIS log (and stdout as fallback)
def _log(msg):
    try:
        QgsMessageLog.logMessage(str(msg), 'InSAR-TS Toolbox', Qgis.Info)
    except Exception:
        print('[InSAR-TS Toolbox]', msg)

# Rectangle map tool for area selection
class RectangleMapTool(QgsMapTool):
    rectangleSelected = pyqtSignal(QgsRectangle)
    
    def __init__(self, canvas):
        super().__init__(canvas)
        self.canvas = canvas
        self.rubber = None
        self.start = None

    def canvasPressEvent(self, e):
        self.start = self.toMapCoordinates(e.pos())
        if self.rubber:
            self.canvas.scene().removeItem(self.rubber)
        self.rubber = QgsRubberBand(self.canvas, QgsWkbTypes.PolygonGeometry)
        self.rubber.setStrokeColor(QColor(0, 0, 0))
        self.rubber.setFillColor(QColor(0, 0, 0, 0))
        self.rubber.setWidth(2)

    def canvasMoveEvent(self, e):
        if not self.start or not self.rubber:
            return
        end = self.toMapCoordinates(e.pos())
        rect = QgsRectangle(self.start, end)
        self.rubber.setToGeometry(QgsGeometry.fromRect(rect), None)

    def canvasReleaseEvent(self, e):
        if not self.start or not self.rubber:
            return
        end = self.toMapCoordinates(e.pos())
        rect = QgsRectangle(self.start, end)
        self.rectangleSelected.emit(rect)
        self.deactivate()

    def deactivate(self):
        try:
            if self.rubber:
                self.canvas.scene().removeItem(self.rubber)
        except Exception:
            pass
        self.rubber = None
        super().deactivate()

# Dialog to select layer and area option
class LayerAreaDialog(QDialog):

    def __init__(self, iface, parent=None):
        super().__init__(parent)
        self.iface = iface
        self.setWindowTitle("Data Properties – Area Selection")
        layout = QVBoxLayout(self)
        hl = QHBoxLayout()
        hl.addWidget(QLabel("Layer:"))
        self.cmbLayer = QComboBox()
        self.layers = [lyr for lyr in QgsProject.instance().mapLayers().values()
                       if isinstance(lyr, QgsVectorLayer)]
        for lyr in self.layers:
            self.cmbLayer.addItem(lyr.name())
        hl.addWidget(self.cmbLayer)
        layout.addLayout(hl)
        self.chkUseROI = QCheckBox("Limit to area (draw rectangle on map)")
        layout.addWidget(self.chkUseROI)
        btns = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        layout.addWidget(btns)
        btns.accepted.connect(self.accept)
        btns.rejected.connect(self.reject)

    def selectedLayer(self):
        if not self.layers:
            return None
        return self.layers[self.cmbLayer.currentIndex()]

# Dialog to select fields and statistics
class StatsChoiceDialog(QDialog):
    def __init__(self, layer, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Data Properties – Fields & Statistics")
        layout = QVBoxLayout(self)
        layout.addWidget(QLabel("Numeric fields:"))
        self.listFields = QListWidget()
        self.listFields.setSelectionMode(QListWidget.MultiSelection)
        for f in layer.fields():
            if f.type() in (QVariant.Int, QVariant.Double):
                it = QListWidgetItem(f.name())
                it.setSelected(True)
                self.listFields.addItem(it)
        layout.addWidget(self.listFields)

        layout.addWidget(QLabel("Statistics:"))
        self.chkMean   = QCheckBox("Mean")
        self.chkMedian = QCheckBox("Median")
        self.chkStd    = QCheckBox("Std. Dev.")
        self.chkMin    = QCheckBox("Min")
        self.chkMax    = QCheckBox("Max")
        self.chkCount  = QCheckBox("Count")
        self.chkHist   = QCheckBox("Histogram")

        for w in (self.chkMean, self.chkMedian, self.chkStd, self.chkMin, self.chkMax, self.chkCount, self.chkHist):
            layout.addWidget(w)
        for w in (self.chkMean, self.chkMedian, self.chkStd, self.chkMin, self.chkMax, self.chkCount):
            w.setChecked(True)

        hl = QHBoxLayout()
        hl.addWidget(QLabel("Histogram bins:"))
        self.spinBins = QSpinBox()
        self.spinBins.setRange(5, 100)
        self.spinBins.setValue(20)
        hl.addWidget(self.spinBins)
        layout.addLayout(hl)
        btns = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        layout.addWidget(btns)
        btns.accepted.connect(self.accept)
        btns.rejected.connect(self.reject)

    def selected_fields(self):
        return [i.text() for i in self.listFields.selectedItems()]

    def requested_stats(self):
        return dict(
            mean=self.chkMean.isChecked(),
            median=self.chkMedian.isChecked(),
            std=self.chkStd.isChecked(),
            min=self.chkMin.isChecked(),
            max=self.chkMax.isChecked(),
            count=self.chkCount.isChecked(),
            histogram=self.chkHist.isChecked(),
            bins=self.spinBins.value()
        )

# Embedded Matplotlib histogram (Qt canvas)
class HistogramCanvas(FigureCanvas):
    """Embedded Matplotlib histogram (Qt canvas) with optional PDF overlay."""
    def __init__(self, vals, field_name, bins=20, parent=None, width=4.2, height=1.8, dpi=110):
        self.fig = Figure(figsize=(width, height), dpi=dpi)
        super().__init__(self.fig)
        self.setParent(parent)

        vals = np.asarray(vals, dtype=float)
        vals = vals[np.isfinite(vals)]
        bins = int(max(5, min(bins, 50)))

        self.ax = self.fig.add_subplot(111)
        self.hist_art = self.ax.hist(vals, bins=bins, edgecolor='black', density=True)
        self.ax.set_title(field_name, fontsize=10, pad=6, fontweight='bold')
        self.ax.set_ylabel("density", fontsize=9)
        self.ax.set_xlabel(field_name, fontsize=9)
        self.ax.tick_params(labelsize=9)
        self.ax.grid(axis='y', linestyle='--', alpha=0.35)
        self._pdf_line = None
        self.ax.xaxis.set_major_locator(MaxNLocator(nbins=5, prune='both'))
        self.ax.xaxis.set_major_formatter(EngFormatter(places=0))
        self.fig.tight_layout(pad=0.8)

    def overlay_pdf(self, x, y):
        if self._pdf_line is None:
            (self._pdf_line,) = self.ax.plot(x, y, linewidth=2.0)
        else:
            self._pdf_line.set_data(x, y)
        self.ax.relim()
        self.ax.autoscale_view()
        self.fig.canvas.draw_idle()

# Embedded Matplotlib time-series (Qt canvas)
class TimeSeriesCanvas(FigureCanvas):

    def __init__(self, dates, values, title="", parent=None, width=8.0, height=3.0, dpi=110):
        self.fig = Figure(figsize=(width, height), dpi=dpi)
        super().__init__(self.fig)
        self.setParent(parent)
        
        # ------------------- TOP: time series plot -------------------
        ax = self.fig.add_subplot(211)
        ax.plot(dates, values, linestyle='-', linewidth=1.2, label='_nolegend_')
        pts = ax.scatter(dates, values, marker='o', color='red', s=10, label='PS measurements')
        ax.legend(handles=[pts], loc='upper right', framealpha=0.9, fontsize=9)
        ax.set_title(title, fontsize=11, pad=6)
        ax.set_xlabel("Year", fontsize=10)
        ax.set_ylabel("Displacement (mm)", fontsize=10)
        ax.grid(True, linestyle='--', alpha=0.35)
        ax.xaxis.set_major_locator(mdates.AutoDateLocator())
        ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(ax.xaxis.get_major_locator()))
        ax.tick_params(labelsize=9)
        
        # ------------------- BOTTOM: spectral analysis -------------------
        # time → years from start
        t_days = np.array([(d - dates[0]).days for d in dates], dtype=float)
        t_yrs  = t_days / 365.25
        y_raw  = np.asarray(values, dtype=float)

        # detrend (linear) to reduce leakage
        try:
            p = np.polyfit(t_yrs, y_raw, 1)
            y_detr = y_raw - (p[0] * t_yrs + p[1])
        except Exception:
            y_detr = y_raw - np.nanmean(y_raw)

        N = len(y_detr)

        # Default outputs for tiny series
        if N < 4:
            freqs_cpy   = np.array([])
            A           = np.array([])
            method_used = "Not enough epochs for spectrum"
        else:
            # --- check sampling regularity ---
            dt_vals = np.diff(t_days)
            if dt_vals.size > 1:
                dt_med = np.median(dt_vals)
                dt_std = np.std(dt_vals)
            else:
                dt_med = 1.0
                dt_std = 0.0

            IRREG_THRESHOLD = 0.05  # 5% relative std → consider irregular
            is_irregular = (dt_std / dt_med) > IRREG_THRESHOLD if dt_med > 0 else False

            # Try to import Lomb–Scargle
            try:
                from scipy.signal import lombscargle
                have_scipy = True
            except Exception:
                have_scipy = False

            freqs_cpy = None
            A = None

            # ---------------------------------------------------------
            # CASE A: Irregular sampling  → Lomb–Scargle PSD (if SciPy)
            # ---------------------------------------------------------
            if is_irregular and have_scipy:
                # frequency grid in cycles/year
                f_ls = np.linspace(0.01, 6.0, 2000)  # adjust max freq if needed
                w = 2.0 * np.pi * f_ls  # angular frequency [rad/year]

                # Lomb–Scargle expects t in same units → t_yrs is fine
                p_ls = lombscargle(t_yrs, y_detr - np.nanmean(y_detr), w, normalize=True)

                # Convert power to amplitude (mm); scaling is approximate but OK for relative comparison
                A = 2.0 * np.sqrt(p_ls)
                freqs_cpy = f_ls
                method_used = "Lomb–Scargle (irregular sampling)"

            # ---------------------------------------------------------
            # CASE B: Regular sampling or fallback → FFT
            # ---------------------------------------------------------
            if freqs_cpy is None or A is None:
                # window with Hann and compensate coherent gain (≈0.5 for Hann)
                w = np.hanning(N)
                cg = w.mean() if np.isfinite(w.mean()) and w.mean() > 0 else 1.0
                y = (y_detr - np.nanmean(y_detr)) * w

                # sampling step in years (median)
                dt_days = dt_med if (np.isfinite(dt_med) and dt_med > 0) else 1.0
                dt_yrs = dt_days / 365.25

                # FFT → frequencies (cycles/year) and properly scaled amplitudes (mm)
                Y = np.fft.rfft(y)
                freqs_cpy = np.fft.rfftfreq(N, d=dt_yrs)      # cycles / year
                A = (2.0 / (N * cg)) * np.abs(Y)              # amplitude in mm
                if A.size > 0:
                    A[0] = 0.0                                # ignore DC

                if is_irregular and not have_scipy:
                    method_used = "FFT (SciPy not available, irregular sampling)"
                else:
                    method_used = "FFT (regular sampling)"

        # --- pick top-k peaks with a minimum separation on the frequency axis ---
        def _topk_with_min_sep(A_arr, f_arr, k=3, min_sep=0.5):
            """Greedy selection of top-k indices in A (by amplitude) such that
            the picked frequencies are at least min_sep apart."""
            if A_arr.size == 0 or f_arr.size == 0:
                return np.array([], dtype=int)
            idx_all = np.arange(A_arr.size)
            idx_sorted = idx_all[np.argsort(A_arr)[::-1]]
            idx_sorted = [i for i in idx_sorted if i != 0]  # drop DC
            chosen = []
            for idx in idx_sorted:
                if len(chosen) >= k:
                    break
                if not chosen:
                    chosen.append(idx)
                    continue
                if np.all(np.abs(f_arr[idx] - f_arr[np.array(chosen)]) >= min_sep):
                    chosen.append(idx)
            return np.array(chosen, dtype=int)

        # -------------------------------------------
        # --- spectrum plot ---
        ax2 = self.fig.add_subplot(212)
        MIN_SEP_CPY = 0.5  # minimum spacing in cycles/year

        if N < 4 or freqs_cpy is None or A is None or len(freqs_cpy) == 0:
            ax2.text(0.5, 0.5, "Not enough data for spectrum",
                     ha="center", va="center", transform=ax2.transAxes)
        else:
            ax2.plot(freqs_cpy, A, linewidth=1.6)
            if A.size > 1:
                topk = _topk_with_min_sep(A, freqs_cpy, k=3, min_sep=MIN_SEP_CPY)
            else:
                topk = np.array([], dtype=int)
            markers = ["o", "s", "^"]
            for i, idx in enumerate(topk):
                fpk = float(freqs_cpy[idx])
                apk = float(A[idx])
                ax2.scatter([fpk], [apk], s=55, marker=markers[i % len(markers)],
                            label=f"{apk:.2f} mm @ {fpk:.3f} cpy", zorder=3)
            if topk.size > 0:
                ax2.axvline(freqs_cpy[topk[0]], linestyle="--", linewidth=1.0, alpha=0.8)

        ax2.set_xlabel("Frequency (cycles/year) (cpr)", fontsize=10)
        ax2.set_ylabel("Amplitude (mm)", fontsize=10)
        ax2.set_title(f"Amplitude Spectrum – {method_used}", fontsize=10, pad=4)
        ax2.grid(True, linestyle="--", alpha=0.35)
        leg = ax2.legend(loc="upper right", frameon=True, framealpha=0.9, fontsize=9)
        self.fig.tight_layout(pad=0.01, h_pad=0.01)
        self.fig.subplots_adjust(left=0.1)




# --- Data Properties Results Dialog ---
class DataPropsResultsDialog(QDialog):

    def __init__(self, parent, title, sections):
        super().__init__(parent)
        self.setWindowTitle(title)

        try:
            import scipy.stats as _st  
            self._have_scipy = True
        except Exception:
            self._have_scipy = False

        self.cards = []  
        root = QVBoxLayout(self)
        scroll = QScrollArea(self); scroll.setWidgetResizable(True)
        root.addWidget(scroll, 1)
        host = QWidget(); scroll.setWidget(host)
        v = QVBoxLayout(host); v.setContentsMargins(6, 6, 6, 6); v.setSpacing(10)


        for idx, sec in enumerate(sections):
            name = sec.get("name", "")
            vals = np.asarray(sec.get("vals", []), dtype=float)
            vals = vals[np.isfinite(vals)]
            bins = int(sec.get("bins", 20))

            box = QGroupBox(name); box_l = QHBoxLayout(box)
            box_l.setContentsMargins(8, 8, 8, 8); box_l.setSpacing(10)

            # LEFT: stats HTML
            stats = QTextBrowser(box)
            stats.setOpenExternalLinks(False)
            stats.setStyleSheet("font-size: 11.5pt;")
            stats.setHtml(sec.get("html", ""))
            stats.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
            stats.setMinimumWidth(260); stats.setMaximumWidth(380)

            # RIGHT: controls + histogram
            right = QWidget(box); rlay = QVBoxLayout(right)
            rlay.setContentsMargins(0, 0, 0, 0)

            # Dist selector
            row = QHBoxLayout()
            row.addWidget(QLabel("Distribution:"))
            combo = QComboBox(right)


            combo.addItem("Normal")
            combo.addItem("Uniform")             # NEW
            combo.addItem("Exponential (+)")     # NEW (positive-support)
            if self._have_scipy:
                combo.addItem("Chi-square (+)")  # NEW (positive-support; needs SciPy)
                combo.addItem("Student-t")
            else:
                combo.setToolTip("SciPy not available; Chi-square and Student-t disabled")



            row.addStretch(1)
            row.addWidget(combo)
            rlay.addLayout(row)
            canvas = HistogramCanvas(vals, name, bins=bins, parent=right, width=5.8, height=1.9, dpi=110)
            canvas.setMinimumHeight(190)
            rlay.addWidget(canvas, 1)
            box_l.addWidget(stats, 0)
            box_l.addWidget(right, 1)
            v.addWidget(box)
            self.cards.append(dict(
                name=name, vals=vals, bins=bins, stats=stats, canvas=canvas, combo=combo
            ))

            # Connect callback
            combo.setProperty("card_index", idx) 
            combo.currentIndexChanged.connect(self._on_combo_changed)

            # Initial fit (Normal)
            self._apply_distribution(idx, combo.currentText())


        v.addStretch(1)
        btns = QDialogButtonBox(QDialogButtonBox.Close)
        btns.rejected.connect(self.reject)
        btns.accepted.connect(self.accept)
        root.addWidget(btns)

    # ---------- helpers ----------
    def _apply_distribution(self, i, dist_name):
        c = self.cards[i]
        vals = c["vals"]
        if vals.size < 2:
            return

        if dist_name.lower().startswith("normal"):
            # Fit Normal: mean & std (MLE)
            mu = float(np.mean(vals))
            sigma = float(np.std(vals, ddof=0))
            pdf_x, pdf_y = self._pdf_normal(vals, mu, sigma)
            stats = self._stats_from_normal(vals, mu, sigma)

        elif dist_name.lower().startswith("student") or dist_name.lower().startswith("t"):
            if not self._have_scipy:
                return
            df, loc, scale = self._fit_student_t(vals)
            pdf_x, pdf_y = self._pdf_t(vals, df, loc, scale)
            stats = self._stats_from_t(vals, df, loc, scale)

        elif dist_name.lower().startswith("uniform"):
            pdf_x, pdf_y = self._pdf_uniform(vals)
            stats = self._stats_from_sample(vals)

        elif dist_name.lower().startswith("exponential"):
            pdf_x, pdf_y = self._pdf_exponential(vals)
            stats = self._stats_from_sample(vals)

        elif dist_name.lower().startswith("chi-square"):
            pdf_x, pdf_y = self._pdf_chisquare(vals)
            stats = self._stats_from_sample(vals)

        else:
            return

        # Update left stats HTML
        html = self._stats_to_html(c["name"], stats)
        c["stats"].setHtml(html)

        # Overlay PDF on histogram
        c["canvas"].overlay_pdf(pdf_x, pdf_y)

    def _on_combo_changed(self, _i):
        combo = self.sender()
        if combo is None:
            return
        idx = combo.property("card_index")
        try:
            idx = int(idx)
        except Exception:
            return
        self._apply_distribution(idx, combo.currentText())


    def _stats_to_html(self, fname, d):
        def fmt(x):
            try: return f"{x:.6g}"
            except Exception: return str(x)
        rows = [
            ("Count", d["count"]),
            ("Mean", d["mean"]),
            ("Median", d["median"]),
            ("Std. Dev.", d["std"]),
            ("Min", d["min"]),
            ("Max", d["max"]),
            *([("df (t)", d["df"])] if "df" in d else []),
        ]
        parts = [
            "<style>table{border-collapse:collapse;} th,td{border:1px solid #ccc;padding:6px 10px;} th{background:#f5f5f5;text-align:left;}</style>",
            f"<div class='field-title' style='font-weight:600;font-size:13pt;margin:0 0 6px 0'>{fname}</div>",
            "<table><tbody>"
        ]
        for k, v in rows:
            parts.append(f"<tr><th>{k}</th><td>{fmt(v)}</td></tr>")
        parts.append("</tbody></table>")
        return "".join(parts)

    # -------- Normal --------
    def _pdf_normal(self, vals, mu, sigma):
        x = np.linspace(np.min(vals), np.max(vals), 400)
        if sigma <= 0 or not np.isfinite(sigma):  # avoid divide-by-zero
            y = np.zeros_like(x)
        else:
            y = (1.0 / (np.sqrt(2*np.pi) * sigma)) * np.exp(-0.5*((x - mu)/sigma)**2)
        return x, y

    def _stats_from_normal(self, vals, mu, sigma):
        return dict(
            count=int(vals.size),
            mean=float(mu),
            median=float(mu),     # for Normal, median==mean
            std=float(sigma),
            min=float(np.min(vals)),
            max=float(np.max(vals)),
        )

    # -------- Student-t --------
    def _fit_student_t(self, vals):
        import scipy.stats as st
        # MLE fit: returns (df, loc, scale)
        df, loc, scale = st.t.fit(vals)  # robust for heavier tails
        return float(df), float(loc), float(scale)

    def _pdf_t(self, vals, df, loc, scale):
        import scipy.stats as st
        x = np.linspace(np.min(vals), np.max(vals), 400)
        y = st.t.pdf((x - loc)/scale, df) / scale
        return x, y

    def _stats_from_t(self, vals, df, loc, scale):
        # Theoretical moments (when defined)
        # mean exists if df>1, variance exists if df>2
        mean = loc if df > 1 else np.nan
        var = (df * scale**2)/(df - 2) if df > 2 else np.nan
        std = np.sqrt(var) if np.isfinite(var) else np.nan
        median = loc  # symmetric
        return dict(
            count=int(vals.size),
            mean=float(mean),
            median=float(median),
            std=float(std) if np.isfinite(std) else np.nan,
            min=float(np.min(vals)),
            max=float(np.max(vals)),
            df=float(df),
        )
    def _stats_from_sample(self, vals):
        vals = np.asarray(vals, dtype=float)
        return dict(
            count=int(vals.size),
            mean=float(np.mean(vals)),
            median=float(np.median(vals)),
            std=float(np.std(vals, ddof=0)),
            min=float(np.min(vals)),
            max=float(np.max(vals)),
        )

    def _pdf_uniform(self, vals):
        # U(a,b) with a=min, b=max
        a = float(np.min(vals)); b = float(np.max(vals))
        if not np.isfinite(a) or not np.isfinite(b) or b <= a:
            x = np.linspace(a, a + 1.0, 400); y = np.zeros_like(x)
            return x, y
        x = np.linspace(a, b, 400)
        y = np.full_like(x, 1.0 / (b - a))
        return x, y

    def _pdf_exponential(self, vals):
        v = np.asarray(vals, dtype=float)
        shift = 0.0
        vmin = float(np.min(v))
        if vmin <= 0:
            shift = -vmin + np.finfo(float).eps
            v = v + shift

        try:
            import scipy.stats as st
            params = st.expon.fit(v, floc=0)      
            scale = float(params[-1])
        except Exception:
            m = float(np.mean(v))
            scale = m if (np.isfinite(m) and m > 0) else 1.0

        x_pos = np.linspace(0, np.max(v), 400)
        y_pos = (1.0 / scale) * np.exp(-x_pos / scale)
        x = x_pos - shift
        return x, y_pos

    def _pdf_chisquare(self, vals):
        if not self._have_scipy:
            x = np.linspace(np.min(vals), np.max(vals), 400)
            return x, np.zeros_like(x)
        import scipy.stats as st
        v = np.asarray(vals, dtype=float)
        shift = 0.0
        vmin = float(np.min(v))
        if vmin <= 0:
            shift = -vmin + np.finfo(float).eps
            v = v + shift
        df, loc, scale = st.chi2.fit(v, floc=0)   # fix loc=0
        x_pos = np.linspace(0, np.max(v), 400)
        y_pos = st.chi2.pdf(x_pos, df, loc=0, scale=scale)
        x = x_pos - shift
        return x, y_pos



# ----------------Functions for utilities ----------------


def ensure_cluster_field(layer) -> int:
    idx = layer.fields().indexFromName('cluster_id')
    if idx != -1:
        return idx

    fld = QgsField('cluster_id', QVariant.Int)   # modern ctor
    fld.setTypeName('Integer')                   # optional, helps some providers
    fld.setLength(10)
    fld.setPrecision(0)

    with edit(layer):
        ok = layer.dataProvider().addAttributes([fld])
        if not ok:
            raise RuntimeError("Failed to add 'cluster_id' field.")
        layer.updateFields()

    return layer.fields().indexFromName('cluster_id')


# ---------------- main plugin ----------------
from .insar_ts_toolbox_dialog import InSAR_TS_ToolboxDialog



# Time-series point picker tool
class TSPointPickTool(QgsMapTool):
    picked = pyqtSignal(object, QgsFeature)   # emits (layer, feature)

    def __init__(self, canvas, layers, iface=None, pixel_tolerance=8):
        super().__init__(canvas)
        self.canvas = canvas
        self.layers = layers if isinstance(layers, (list, tuple)) else [layers]
        self.iface = iface
        self.pixel_tolerance = int(max(2, pixel_tolerance))
        self.setCursor(Qt.CrossCursor)

    def canvasReleaseEvent(self, e):
        pt = self.toMapCoordinates(e.pos())
        tol_mu = self.pixel_tolerance * self.canvas.mapUnitsPerPixel()
        search_rect = QgsRectangle(pt.x() - tol_mu, pt.y() - tol_mu, pt.x() + tol_mu, pt.y() + tol_mu)
        click_geom = QgsGeometry.fromPointXY(QgsPointXY(pt))

        best = (None, None, float("inf"))  # (layer, feature, distance)

        for lyr in self.layers:
            # skip hidden / non-point layers just in case
            try:
                node = QgsProject.instance().layerTreeRoot().findLayer(lyr.id())
                if not node or not node.isVisible() or lyr.geometryType() != QgsWkbTypes.PointGeometry:
                    continue
            except Exception:
                continue

            req = QgsFeatureRequest().setFilterRect(search_rect)
            feats = list(lyr.getFeatures(req))
            if not feats:
                continue

            # nearest feature center to click
            for ft in feats:
                try:
                    d = ft.geometry().closestSegmentWithContext(pt)[0]
                except Exception:
                    d = ft.geometry().distance(click_geom)
                if d < best[2]:
                    best = (lyr, ft, d)

        if best[0] is None:
            # nice message but non-blocking
            try:
                self.iface.messageBar().pushMessage(
                    "TS Analysis", "No visible point feature under cursor.", level=Qgis.Info, duration=2
                )
            except Exception:
                pass
            return

        self.picked.emit(best[0], best[1])


from qgis.PyQt.QtCore import QObject, QEvent

class _DlgGuard(QObject):
    """Stops TS picker when the toolbox dialog hides/closes on any platform/Qt build."""
    def __init__(self, owner):
        super().__init__()
        self._owner = owner  # InSAR_TS_Toolbox instance

    def eventFilter(self, obj, ev):
        # Build a set of supported event types defensively
        types = {QEvent.Hide, QEvent.Close, QEvent.WindowStateChange}
        if hasattr(QEvent, "HideToParent"):   # not always present
            types.add(getattr(QEvent, "HideToParent"))

        if ev.type() in types:
            try:
                self._owner._stop_ts_pick()   # force-pan inside
            except Exception:
                pass
        return False




# ---------------- main plugin ----------------

# Main plugin class for QGIS InSAR-TS Toolbox
class InSAR_TS_Toolbox:

    def __init__(self, iface):
        self.iface = iface
        self.dlg = None
        self._rectTool = None
        self._prevTool = None
        self._tsPickTool = None

    # ---------------- GUI ----------------
    def _ensure_dialog(self):
        # --- remove any legacy guard/event filter from prior versions ---
        try:
            if getattr(self, "dlg", None) is not None and hasattr(self, "_dlgGuard") and self._dlgGuard:
                try:
                    self.dlg.removeEventFilter(self._dlgGuard)
                except Exception:
                    pass
                self._dlgGuard = None
        except Exception:
            pass
        if self.dlg is None:
            self.dlg = InSAR_TS_ToolboxDialog()
            # Ensure picker stops when dialog closes/hides, without event filters
            def _wrap_close(ev):
                try:
                    self._stop_ts_pick()
                finally:
                    # call base implementation
                    try:
                        super(type(self.dlg), self.dlg).closeEvent(ev)
                    except Exception:
                        ev.accept()

            def _wrap_hide(ev):
                try:
                    self._stop_ts_pick()
                finally:
                    try:
                        super(type(self.dlg), self.dlg).hideEvent(ev)
                    except Exception:
                        ev.accept()

            self.dlg.closeEvent = _wrap_close
            self.dlg.hideEvent  = _wrap_hide

            # Also for destruction via QObject::destroyed
            self.dlg.destroyed.connect(lambda _obj=None: self._stop_ts_pick())


            self.dlg.resize(1000, 700)
            self.dlg.setWindowTitle("InSAR-TS Toolbox")
            btn_cluster = getattr(self.dlg, 'btnRunCluster', None) or getattr(self.dlg, 'btnRun', None)
            if btn_cluster:
                try: btn_cluster.clicked.disconnect()
                except Exception: pass
                btn_cluster.clicked.connect(self.run_clustering)

            btn_dp = getattr(self.dlg, 'btnRunDataProps', None)
            if btn_dp:
                try: btn_dp.clicked.disconnect()
                except Exception: pass
                btn_dp.clicked.connect(self.on_data_properties)

            self.dlg.comboAlgorithm.currentTextChanged.connect(self.on_algorithm_changed)
            self.dlg.stackedParams.currentChanged.connect(self._on_params_page_changed)
            
            # Inject TS Analysis tab entirely in code
            self._inject_ts_tab()
            self._inject_help_tab()
            self.dlg.accepted.connect(self._stop_ts_pick)
            self.dlg.rejected.connect(self._stop_ts_pick)
            self.dlg.finished.connect(lambda _code: self._stop_ts_pick())
          
        return self.dlg

    # --- TS Analysis tab (created in code) ---
    def _inject_ts_tab(self):

        dlg = self.dlg
        tabw = dlg.findChild(QTabWidget)
        if tabw is None:
            tabw = QTabWidget(dlg)
            content = QWidget()
            lay = QVBoxLayout(content)
            while dlg.layout().count():
                item = dlg.layout().takeAt(0)
                w = item.widget()
                if w:
                    lay.addWidget(w)
            tabw.addTab(content, "Main")
            dlg.layout().addWidget(tabw)

        # --- Tab ---
        tab = QWidget(dlg)
        root = QVBoxLayout(tab)

        # Top row: pick button + info
        top = QHBoxLayout()
        self.btnPickTS = QPushButton("Pick a point on map", tab)
        self.lblTSInfo = QLabel("No point selected.", tab)
        self.lblTSInfo.setStyleSheet("color:#666;")
        top.addWidget(self.btnPickTS, 0)
        top.addWidget(self.lblTSInfo, 1)
        root.addLayout(top)

        # === Splitter (plot left | attributes right) ===
        splitter = QSplitter(Qt.Horizontal, tab)

        # Left: plot container
        left = QWidget(splitter)
        left.setObjectName("frameTSPlot")
        left.setLayout(QVBoxLayout())
        left.layout().setContentsMargins(0, 0, 0, 0)
        self.frameTSPlot = left
        left.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        # Right: attributes (scrollable)
        right = QWidget(splitter)
        right_v = QVBoxLayout(right)
        right_v.setContentsMargins(6, 6, 6, 6)

        hdr = QLabel("Attributes")
        hdr.setStyleSheet("font-weight:600; margin:2px 0 8px 0;")
        right_v.addWidget(hdr, 0)

        self.featuresScroll = QScrollArea(right)
        self.featuresScroll.setWidgetResizable(True)
        self.featuresHost = QWidget()
        self.featuresForm = QFormLayout(self.featuresHost)
        self.featuresForm.setLabelAlignment(Qt.AlignLeft)
        self.featuresForm.setFormAlignment(Qt.AlignTop)
        self.featuresScroll.setWidget(self.featuresHost)
        self.featuresScroll.setFrameShape(QFrame.StyledPanel)
        right_v.addWidget(self.featuresScroll, 1)

        splitter.addWidget(left)
        splitter.addWidget(right)

        splitter.setStretchFactor(0, 3)   # plots
        splitter.setStretchFactor(1, 1)   # attributes
        QTimer.singleShot(0, lambda: splitter.setSizes([700, 300]))
        root.addWidget(splitter, 1)
        tabw.addTab(tab, "TS Analysis")

        try:
            self.btnPickTS.clicked.disconnect()
        except Exception:
            pass
        self.btnPickTS.clicked.connect(self.start_ts_pick)
    def _show_about_dialog(self):
        from qgis.PyQt.QtWidgets import QMessageBox

        text = f"""
        <h2>InSAR-TS Toolbox</h2>
        <p><b>Version:</b> {PLUGIN_VERSION}</p>

        <p>This QGIS plugin was developed at the
        Geodätisches Institut Hannover (GIH), Leibniz University Hannover, 
        by Ashwin Kumar Dhanasekaran, M. Sc., in collaboration with Kourosh Shahryarinia and Dr.-Ing. Mohammad Omidalizarandi. 
        </p>
        <p>It provides a comprehensive suite of tools for 
        processing and analyzing InSAR time-series data, including:</p>

        <ul class="features">
            <li><strong>Clustering Algorithms:</strong> For grouping and identifying areas with similar deformation characteristics.</li>
            <li><strong>Statistical Analysis:</strong> To derive meaningful metrics and assess the quality of the time-series.</li>
            <li><strong>Spectral Analysis:</strong> For characterizing and isolating temporal deformation signals.</li>
        </ul>
        <h3>Acknowledgements</h3>
        <p>Developed at the Geodätisches Institut Hannover (GIH),
        Leibniz University Hannover.</p>
        <p>This work was supported by a DAAD (German Academic Exchange Service)
        Research Grant.</p>

        <h3>Citation</h3>
        <p>If you use InSAR-TS Toolbox in your research, please cite:</p>
        <p>
        A. K. Dhanasekaran, K. Shahryarinia, M. Omidalizarandi,  
        <i>InSAR-TS Toolbox: A QGIS plugin for clustering and spectral analysis of
        InSAR time series</i>, 2025 (in preparation).
        </p>

        <h3>Links</h3>
        <ul>
          <li><a href="{GITHUB_URL}">Source code on GitHub</a></li>
          <li><a href="{GITHUB_URL}/issues">Bug reports &amp; feature requests</a></li>
        </ul>

        <p>&copy; 2025 – Ashwin Kumar Dhanasekaran et al.</p>
        """

        mb = QMessageBox(self.iface.mainWindow())
        mb.setWindowTitle("About InSAR-TS Toolbox")
        mb.setIcon(QMessageBox.Information)
        mb.setTextFormat(Qt.RichText)
        mb.setText(text)
        mb.setStandardButtons(QMessageBox.Ok)
        mb.exec_()

    def _inject_help_tab(self):

        dlg = self.dlg
        tabw = dlg.findChild(QTabWidget)
        if tabw is None:
            return 

        tab = QWidget(dlg)
        root = QVBoxLayout(tab)
        root.setContentsMargins(8, 8, 8, 8)

        helpBox = QTextBrowser(tab)
        helpBox.setOpenExternalLinks(False)
        helpBox.setOpenLinks(False)
        helpBox.anchorClicked.connect(self._on_help_anchor_clicked)
        helpBox.setStyleSheet("font-size: 11pt; font-family: Segoe UI, Arial, sans-serif;")
        helpBox.setReadOnly(True)

        help_html = f"""
        <style>
        h2{{margin:0 0 12px 0; font-size: 14pt;}}
        h3{{margin:14px 0 6px 0; font-size: 12pt;}}
        ul{{margin:6px 0 10px 22px}}
        li{{margin-bottom:6px; line-height:1.4;}}
        code{{background:#f2f2f2;padding:1px 4px;border-radius:3px}}
        </style>

        <h2>InSAR-TS Toolbox</h2>

        <h3>Overview of Tabs</h3>

        <h4>Clustering</h4>
        <p>Select numeric fields from a point layer and run clustering with
        <b>KMeans</b> or <b>DBSCAN</b>. Results are written to the <code>cluster_id</code> field
        and visualized with automatic color symbology (noise in grey).</p>

        <ul>
            <li>
                <b>K-Means</b>: partitions points into <i>k</i> clusters by minimizing the 
                distance to the cluster centroid.  
                Best for compact, spherical clusters with similar variance.
                <ul>
                    <li><b>n_clusters</b>: number of clusters to create (must be chosen by user).</li>
                </ul>
            </li>

            <li>
                <b>DBSCAN</b>: density-based clustering that groups points with many neighbours
                and labels isolated points as noise.  
                Ideal for clusters of arbitrary shape and data with outliers.
                <ul>
                    <li><b>eps</b>: radius of the neighbourhood (distance threshold).</li>
                    <li><b>min_samples</b>: minimum number of points required to form a dense region.</li>
                </ul>
            </li>

            <li>
                Learn more:
                <a href="https://scikit-learn.org/stable/modules/clustering.html" target="_blank">
                    scikit-learn clustering guide
                </a>
            </li>
        </ul>

        <h4>Data Properties</h4>
        <p>Compute descriptive statistics (<i>mean, median, std, min, max, count</i>) for
        selected fields, either across the whole layer or within a region of interest (ROI).
        Histograms are provided with optional distribution fits
        (Normal, Student-t, Uniform, Exponential, Chi-square).</p>

        <h4>Analysis</h4>
        <p>Click on a point feature in a time-series dataset to display its displacement
        time series and corresponding amplitude spectrum. The three strongest spectral peaks
        are automatically highlighted and reported in the legend.</p>

        <h4>Attributes</h4>
        <p>The right-hand panel lists all attributes for the chosen feature.</p>

        <h4>TS Analysis Methods</h4>
        <ul>
        <li><b>FFT (Fast Fourier Transform)</b>: used when sampling is approximately regular.
        Efficiently computes frequencies present in the time series.
        <a href="https://en.wikipedia.org/wiki/Fast_Fourier_transform" target="_blank">Learn more</a></li>

        <li><b>Lomb–Scargle Periodogram</b>: used when sampling is irregular (typical for InSAR).
        Produces a frequency spectrum without requiring equally spaced measurements.
        <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.lombscargle.html" target="_blank">Learn more</a></li>

        <li>The toolbox automatically chooses the appropriate method based on sampling regularity.</li>
        </ul>

        <h4>TS Analysis Tips</h4>
        <ul>
            <li>
                <b>Time normalization:</b>  
                All acquisition dates are converted into decimal years relative to the first epoch.  
                This provides a uniform time axis and makes frequency interpretation easier 
                (e.g., 1 cycle/year ≈ annual signal).
            </li>

            <li>
                <b>Detrending + Hann window:</b>  
                The linear trend of the displacement time series is removed before spectral analysis.  
                A Hann window is applied to suppress edge discontinuities, which reduces 
                spectral leakage and gives more accurate frequency peaks.
            </li>

            <li>
                <b>Automatic method selection (FFT vs. Lomb–Scargle):</b>  
                The plugin checks the sampling intervals between acquisition dates:  
                if they are approximately uniform, a Fast Fourier Transform (FFT) is used;  
                if sampling is uneven (common in InSAR), the Lomb–Scargle periodogram is used.  
                Lomb–Scargle is specifically designed for irregular time series and avoids the
                distortions that FFT would produce in such cases.
            </li>
        </ul>

        <h4>Requirements</h4>
        <p><b>numpy</b>, <b>pandas</b>, <b>matplotlib</b> and <b>scipy</b> ship with the
        standard QGIS installers and need no action.</p>
        <p><b>scikit-learn</b> is <i>not</i> bundled with QGIS and is required only by the
        Clustering tab. To install it, open the OSGeo4W Shell (Windows) and run
        <code>python -m pip install scikit-learn</code>, or on Linux/macOS run
        <code>python3 -m pip install scikit-learn</code> against the Python that QGIS uses.
        Restart QGIS afterwards.</p>

        <h4>Troubleshooting</h4>
        <ul>
        <li><b>No feature under cursor</b>: zoom in and try again (picker uses a small pixel tolerance).</li>
        <li><b>No time-series fields found</b>: ensure fields are named like <code>YYYYMMDD</code> and contain numeric values.</li>
        <li><b>Empty stats</b>: ensure numeric fields were selected and ROI contains features.</li>
        </ul>

        <h4>Acknowledgements</h4>
        <p>Developed at the Geodätisches Institut Hannover (GIH),
        Leibniz University Hannover. This work was supported by a
        DAAD (German Academic Exchange Service) Research Grant.</p>

        <h4>More info</h4>

        <p style="margin-top:10px;">
          <a href="about:insar-ts-toolbox">About InSAR-TS Toolbox</a>
        </p>
        """


        helpBox.setHtml(help_html)
        root.addWidget(helpBox, 1)
        tabw.addTab(tab, "Help")



    def _on_help_anchor_clicked(self, url: QUrl):
        s = url.toString()
        # internal "about" link from Help tab
        if s.startswith("about:insar-ts-toolbox"):
            self._show_about_dialog()
            return

        # everything else → open in browser
        try:
            self._open_url_external(s)
        except Exception:
            QDesktopServices.openUrl(QUrl(s))


    def _force_pan(self):
        """Hard switch to Pan tool to guarantee picker is gone."""
        try:
            self.iface.actionPan().trigger()
        except Exception:
            pass

    def _is_ts_pick_active(self):
        try:
            mt = self.iface.mapCanvas().mapTool()
            # Avoid circular import: refer to class by name
            return mt is not None and mt.__class__.__name__ == "TSPointPickTool"
        except Exception:
            return False



    def _open_url_external(self, url_str: str):

        chrome_path = None
        if os.name == "nt":  # Windows
            # Try PATH first
            chrome_path = shutil.which("chrome") or shutil.which("chrome.exe")
            # Common install locations
            if not chrome_path:
                candidates = [
                    os.path.join(os.environ.get("PROGRAMFILES", ""), "Google", "Chrome", "Application", "chrome.exe"),
                    os.path.join(os.environ.get("PROGRAMFILES(X86)", ""), "Google", "Chrome", "Application", "chrome.exe"),
                    os.path.join(os.environ.get("LOCALAPPDATA", ""), "Google", "Chrome", "Application", "chrome.exe"),
                ]
                chrome_path = next((p for p in candidates if p and os.path.exists(p)), None)

        if chrome_path and os.path.exists(chrome_path):
            # Launch Chrome detached so QGIS isn't blocked
            QProcess.startDetached(chrome_path, [url_str])
            return

        # Non-Windows or Chrome not found → open with default browser
        QDesktopServices.openUrl(QUrl(url_str))


    def _restore_canvas_tool(self, force_pan=False):
        try:
            canvas = self.iface.mapCanvas()
            tool = getattr(self, "_rectTool", None)
            prev = getattr(self, "_prevTool", None)

            if tool is not None:
                try:
                    if canvas.mapTool() is tool:
                        canvas.unsetMapTool(tool)
                except Exception:
                    pass

            if prev is not None and not force_pan:
                try:
                    canvas.setMapTool(prev)
                except Exception:
                    force_pan = True

            if force_pan or prev is None:
                try:
                    self.iface.actionPan().trigger()
                except Exception:
                    pass
        finally:
            self._rectTool = None
            self._prevTool = None
    def _reset_ts_tab(self):
        """Clear TS Analysis UI so the toolbox opens fresh."""
        # stop any active pick tool
        try:
            self._stop_ts_pick()
        except Exception:
            pass

        # clear plot container
        container = getattr(self, 'frameTSPlot', None)
        if container and container.layout():
            for c in container.findChildren(QWidget):
                c.setParent(None)
                c.deleteLater()

        # reset right-hand attributes panel
        if hasattr(self, "featuresForm") and self.featuresForm:
            while self.featuresForm.count():
                item = self.featuresForm.takeAt(0)
                w = item.widget()
                if w:
                    w.deleteLater()

        # reset info/btn text
        if hasattr(self, 'lblTSInfo') and self.lblTSInfo:
            self.lblTSInfo.setText("No point selected.")
        if hasattr(self, 'btnPickTS') and self.btnPickTS:
            self.btnPickTS.setText("Pick a point on map")

    def initGui(self):
        icon = QIcon(os.path.join(os.path.dirname(__file__), "icon.png"))
        self.action = QAction(icon, "InSAR-TS Toolbox", self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addToolBarIcon(self.action)
        self.iface.addPluginToMenu("InSAR-TS Toolbox", self.action)
    def _is_layer_visible(self, layer) -> bool:
        try:
            node = QgsProject.instance().layerTreeRoot().findLayer(layer.id())
            return bool(node and node.isVisible())
        except Exception:
            # If we can't resolve visibility (shouldn't happen), be conservative
            return False

    def unload(self):
        try:
            if getattr(self, "dlg", None) is not None and hasattr(self, "_dlgGuard") and self._dlgGuard:
                try:
                    self.dlg.removeEventFilter(self._dlgGuard)
                except Exception:
                    pass
                self._dlgGuard = None
        except Exception:
            pass
        try:
            self._stop_ts_pick()
        except Exception:
            pass
        self._reset_ts_tab()
        self.iface.removePluginMenu("InSAR-TS Toolbox", self.action)
        self.iface.removeToolBarIcon(self.action)


    def run(self):
        self._ensure_dialog()
        self._reset_ts_tab()
        self.populate_feature_combo()
        self.on_algorithm_changed(self.dlg.comboAlgorithm.currentText())
        self.dlg.show()

    # ---------------- Dialog setup ----------------
    def populate_feature_combo(self):
        layer = self.iface.activeLayer()
        if not layer or not layer.type() == QgsMapLayer.VectorLayer:
            return

        numeric = [f.name() for f in layer.fields() if f.type() in (QVariant.Int, QVariant.Double)]
        lst = self.dlg.listFeatures
        lst.clear()
        for name in numeric:
            item = QListWidgetItem(name)
            item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
            item.setCheckState(Qt.Unchecked)
            lst.addItem(item)


    def on_algorithm_changed(self, name: str):
        name_l = (name or "").strip().lower()
        mapping = {'kmeans': 'pageKMeans', 'dbscan': 'pageDBSCAN'}
        target = mapping.get(name_l)
        if target:
            for i in range(self.dlg.stackedParams.count()):
                if self.dlg.stackedParams.widget(i).objectName() == target:
                    self.dlg.stackedParams.setCurrentIndex(i)
                    break

    def _on_params_page_changed(self, index):
        pass

    # -------- clustering --------
    def _require_sklearn(self):
        try:
            from sklearn.cluster import KMeans, DBSCAN
            from sklearn.preprocessing import StandardScaler
            return KMeans, DBSCAN, StandardScaler
        except Exception as e:
            QMessageBox.critical(
                self.iface.mainWindow(), "Missing dependency",
                "scikit-learn is required for the Clustering tab, but it is not "
                "installed in the Python environment used by QGIS.\n\n"
                "On Windows, open the OSGeo4W Shell and run:\n"
                "    python -m pip install scikit-learn\n\n"
                "On Linux/macOS, run:\n"
                "    python3 -m pip install scikit-learn\n\n"
                "Restart QGIS afterwards. The other tabs work without it.\n\n"
                f"Details: {e}")
            raise

    def run_clustering(self):
        layer = self.iface.activeLayer()
        if not layer:
            QMessageBox.critical(self.iface.mainWindow(), "Error", "No active layer selected.")
            return
        if layer.geometryType() != QgsWkbTypes.PointGeometry:
            QMessageBox.critical(self.iface.mainWindow(), "Error", "Selected layer is not a point layer.")
            return
        if layer.providerType() == 'delimitedtext':
            QMessageBox.information(self.iface.mainWindow(), "CSV Layer", "CSV detected. Copying to memory layer.")
            mem = QgsVectorLayer(f"Point?crs={layer.crs().authid()}", "Editable Copy", "memory")
            mem.dataProvider().addAttributes(layer.fields()); mem.updateFields()
            mem.dataProvider().addFeatures(list(layer.getFeatures()))
            QgsProject.instance().addMapLayer(mem, addToLegend=True)
            self.iface.setActiveLayer(mem)
            layer = mem

        algo = (self.dlg.comboAlgorithm.currentText() or "").strip().lower()

        selected = [self.dlg.listFeatures.item(i).text()
                    for i in range(self.dlg.listFeatures.count())
                    if self.dlg.listFeatures.item(i).checkState() == Qt.Checked]
        if not selected:
            QMessageBox.warning(self.iface.mainWindow(), "No Features Selected", "Select at least one field.")
            return

        params = {}
        if algo == 'kmeans':
            params['algo'] = 'KMeans'
            params['n_clusters'] = self.dlg.spinKMeansClusters.value()
        elif algo == 'dbscan':
            self.dlg.spinDBSCANeps.interpretText()
            params['algo'] = 'DBSCAN'
            params['eps'] = self.dlg.spinDBSCANeps.value()
            params['min_samples'] = self.dlg.spinDBSCANminPts.value()
        else:
            QMessageBox.critical(self.iface.mainWindow(), "Error", f"Unknown algorithm: {algo}")
            return

        try:
            self.perform_clustering(layer, params, selected)
            idx = layer.fields().indexFromName("cluster_id")
            vals = set(layer.dataProvider().uniqueValues(idx))
            n = len({v for v in vals if v != -1})
            QMessageBox.information(self.iface.mainWindow(), "Clustering Complete",
                                    f"{params['algo']} finished with {n} clusters.")
            self.symbolize_clusters(layer)
        except Exception as e:
            QMessageBox.critical(self.iface.mainWindow(), "Clustering Error", repr(e))

    def perform_clustering(self, layer, params, selected_fields):
        KMeans, DBSCAN, StandardScaler = self._require_sklearn()
        feats = list(layer.getFeatures())

        idxs = [layer.fields().indexFromName(f) for f in selected_fields]
        rows = []
        for ft in feats:
            row = []
            for idx in idxs:
                v = ft[idx]
                try:
                    row.append(float(v))
                except Exception:
                    row.append(np.nan)
            rows.append(row)

        X = np.array(rows, dtype=float)
        X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)
        X = StandardScaler(with_mean=True, with_std=True).fit_transform(X)

        if params['algo'] == 'KMeans':
            model = KMeans(n_clusters=int(params['n_clusters']), n_init=10, random_state=0)
        else:
            model = DBSCAN(eps=float(params['eps']), min_samples=int(params['min_samples']))
        labels = model.fit_predict(X)

        idx = ensure_cluster_field(layer)

        must_commit = False
        if not layer.isEditable():
            layer.startEditing()
            must_commit = True

        try:
            for ft, lab in zip(feats, labels):
                layer.changeAttributeValue(ft.id(), idx, int(lab))
            if must_commit:
                if not layer.commitChanges():
                    layer.rollBack()
                    raise RuntimeError("Commit failed: " + "; ".join(layer.commitErrors()))
        except Exception:
            if must_commit:
                layer.rollBack()
            raise

    def symbolize_clusters(self, layer):
        idx = layer.fields().indexFromName("cluster_id")
        vals = sorted(set(layer.dataProvider().uniqueValues(idx)))
        cats = []
        style = QgsStyle().defaultStyle()
        ramp = style.colorRamp('Spectral') or style.colorRamp('Random colors')

        nvals = max(1, len(vals))
        for i, v in enumerate(vals):
            sym = QgsSymbol.defaultSymbol(layer.geometryType())
            if v == -1:
                sym.setColor(QColor(150, 150, 150))  # noise as gray
            elif ramp and nvals > 1:
                t = 0.0 if nvals == 1 else (i / float(nvals - 1))
                sym.setColor(ramp.color(t))
            label = "Noise (-1)" if v == -1 else f"Cluster {int(v)}"
            cats.append(QgsRendererCategory(v, sym, label))
        layer.setRenderer(QgsCategorizedSymbolRenderer("cluster_id", cats))
        layer.triggerRepaint()

    def _render_feature_attributes(self, layer, feature, title_prefix="Attributes"):

        # Clear previous rows
        if hasattr(self, "featuresForm") and self.featuresForm:
            while self.featuresForm.count():
                item = self.featuresForm.takeAt(0)
                w = item.widget()
                if w:
                    w.deleteLater()

        if not hasattr(self, "featuresForm") or self.featuresForm is None:
            return  
        
        # Build a mask for time-series fields
        ts_name_re = re.compile(r'^\d{6,8}$')   # e.g., 20190106 / 2019...

        # Optional header row
        hdr = QLabel(f"{title_prefix} for ID #{feature.id()}")
        hdr.setStyleSheet("font-weight: 600; margin: 6px 0;")
        self.featuresForm.addRow(hdr, QLabel(""))

        # Iterate attributes
        attrs = feature.attributes()
        fields = layer.fields()

   
        for idx, fld in enumerate(fields):
            name = fld.name()
            if ts_name_re.match(name): 
                continue
    
            if name.lower() in {"x", "y"} and layer.geometryType() != QgsWkbTypes.PointGeometry:
                pass  

            val = attrs[idx]
            if val is None:
                sval = "—"
            else:
                try:
                    if isinstance(val, (int, np.integer)):
                        sval = f"{int(val)}"
                    elif isinstance(val, (float, np.floating)):
                        sval = f"{float(val):.3f}"
                    else:
                        sval = str(val)
                except Exception:
                    sval = str(val)

            key_lbl = QLabel(name + ":")
            val_lbl = QLabel(sval)
            val_lbl.setTextInteractionFlags(Qt.TextSelectableByMouse)
            self.featuresForm.addRow(key_lbl, val_lbl)

        # -------- TS Analysis (pick & plot) --------
    def _visible_point_layers_in_render_order(self):
        root = QgsProject.instance().layerTreeRoot()
        # Prefer render order from the layer tree (top-first)
        try:
            render_order = list(root.layerOrder())  # list[QgsMapLayer]
        except Exception:
            # Fallback: whatever order we can get
            render_order = [n.layer() for n in root.findLayers()]

        result = []
        for lyr in render_order:
            if isinstance(lyr, QgsVectorLayer) and lyr.geometryType() == QgsWkbTypes.PointGeometry:
                node = root.findLayer(lyr.id())
                if node and node.isVisible():
                    result.append(lyr)
        return result

    def start_ts_pick(self):
        layer = self.iface.activeLayer()
        if self._tsPickTool: 
            self._stop_ts_pick()
            return

        if not layer or layer.geometryType() != QgsWkbTypes.PointGeometry:
            QMessageBox.warning(self.iface.mainWindow(), "TS Analysis",
                                "Please select a point layer as active.")
            return
        
        if not self._is_layer_visible(layer):
            QMessageBox.warning(self.iface.mainWindow(), "TS Analysis",
                                f"Active layer '{layer.name()}' is hidden. "
                                "Make it visible in the Layers panel to pick points.")
            return
        canvas = self.iface.mapCanvas()
        self._prevTool = canvas.mapTool()
        self._tsPickTool = TSPointPickTool(self.iface.mapCanvas(), layer, iface=self.iface, pixel_tolerance=8)

        self._tsPickTool.picked.connect(self._on_ts_point_picked)
        canvas.setMapTool(self._tsPickTool)

        if hasattr(self, 'lblTSInfo') and self.lblTSInfo:
            self.lblTSInfo.setText("Picking… click a point feature on the map.")
        if hasattr(self, 'btnPickTS') and self.btnPickTS:
            self.btnPickTS.setText("Stop picking")

    def _stop_ts_pick(self):
        canvas = self.iface.mapCanvas()
        try:
            mt = canvas.mapTool()

            # If our attribute holds a tool and it's active, unset it
            if getattr(self, "_tsPickTool", None) and mt is self._tsPickTool:
                try:
                    canvas.unsetMapTool(self._tsPickTool)
                except Exception:
                    pass

            # Belt-and-suspenders: if ANY TSPointPickTool is active, unset it
            if mt is not None and mt.__class__.__name__ == "TSPointPickTool":
                try:
                    canvas.unsetMapTool(mt)
                except Exception:
                    pass

        except Exception:
            pass
        finally:
            # Always switch to Pan as a safe default
            self._force_pan()

            # Drop refs so GC can collect the tool
            self._tsPickTool = None
            self._prevTool = None

            # UI text reset
            if hasattr(self, 'lblTSInfo') and self.lblTSInfo:
                self.lblTSInfo.setText("Picking stopped.")
            if hasattr(self, 'btnPickTS') and self.btnPickTS:
                self.btnPickTS.setText("Pick a point on map")


    def _restore_tool_after_ts(self):
        try:
            canvas = self.iface.mapCanvas()
            if getattr(self, "_tsPickTool", None) and canvas.mapTool() is self._tsPickTool:
                canvas.unsetMapTool(self._tsPickTool)
        except Exception:
            pass
        finally:
            self._tsPickTool = None
            if getattr(self, "_prevTool", None):
                try:
                    self.iface.mapCanvas().setMapTool(self._prevTool)
                except Exception:
                    pass
            self._prevTool = None

    def _on_ts_point_picked(self, layer, feature):

        ts_fields = []
        for fld in layer.fields():
            name = fld.name()
            if re.match(r'^\d+', name):
                ts_fields.append(name)

        if not ts_fields:
            QMessageBox.information(self.iface.mainWindow(), "TS Analysis",
                                    "No time-series fields found (fields starting with a date).")
            return

        dates = pd.to_datetime(ts_fields, format='%Y%m%d', errors='coerce')
        keep = ~pd.isna(dates)
        ts_pairs = [(d, n) for d, n, k in zip(dates, ts_fields, keep) if k]
        if not ts_pairs:
            QMessageBox.information(self.iface.mainWindow(), "TS Analysis",
                                    "Fields looked numeric but didn’t parse as YYYYMMDD.")
            return
        ts_pairs.sort(key=lambda x: x[0])

        xs, ys = [], []
        for d, name in ts_pairs:
            try:
                v = feature[name]
            except KeyError:
                continue
            if v is None:
                continue
            try:
                v = float(v)
            except Exception:
                continue
            xs.append(d)
            ys.append(v)

        if len(xs) == 0:
            QMessageBox.information(self.iface.mainWindow(), "TS Analysis",
                                    "Selected feature has no numeric values in the time-series fields.")
            return

        container = getattr(self, 'frameTSPlot', None)
        if container is None:
            QMessageBox.warning(self.iface.mainWindow(), "TS Analysis",
                                "Plot container not found.")
            return

        for c in container.findChildren(QWidget):
            c.setParent(None)
            c.deleteLater()

        canvas = TimeSeriesCanvas(xs, ys, title=f"Time series for ID #{feature.id()} – Displacement")
        container.layout().addWidget(canvas)

        if hasattr(self, 'lblTSInfo') and self.lblTSInfo:
            lyr_name = layer.name() if layer is not None else "—"
            self.lblTSInfo.setText(
                f"Layer: {lyr_name}  •  Feature ID: {feature.id()}  •  {len(xs)} epochs"
            )

        self.dlg.setWindowModality(Qt.NonModal)
        self.dlg.setWindowState(self.dlg.windowState() & ~Qt.WindowMinimized)
        self._render_feature_attributes(layer, feature, title_prefix="Attributes")

        self.dlg.show()
        self.dlg.raise_()
        self.dlg.activateWindow()

    

    def _data_props_show_intro(self) -> bool:

        s = QSettings()
        key = "insar_ts_toolbox/data_props_intro_suppressed"
        if s.value(key, type=bool):
            return True

        mb = QMessageBox(self.iface.mainWindow())
        mb.setIcon(QMessageBox.Information)
        mb.setWindowTitle("Data Properties – How it works")
        mb.setText(
            "This tool computes summary statistics and inline histograms for a chosen layer or ROI."
        )
        mb.setInformativeText(
            "Steps:\n"
            "1) Pick a vector layer (points/polygons) to analyze.\n"
            "2) (Optional) Limit to a map rectangle (ROI).\n"
            "3) Choose numeric fields and which stats to compute.\n\n"
            "Press OK to continue."
        )
        cb = QCheckBox("Don’t show this again")
        mb.setCheckBox(cb)
        mb.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        mb.setDefaultButton(QMessageBox.Ok)

        res = mb.exec_()
        if cb.isChecked():
            s.setValue(key, True)

        return res == QMessageBox.Ok


   
    def on_data_properties(self):

        if not self._data_props_show_intro():
            return
        parent = self._ensure_dialog()

        d = LayerAreaDialog(self.iface, parent)
        if not d.exec_():
            return
        layer = d.selectedLayer()
        if layer is None:
            QMessageBox.warning(self.iface.mainWindow(), "Data Properties", "No vector layer selected.")
            return
        roi_needed = d.chkUseROI.isChecked()

        def proceed_with_rect(rect):

            sd = StatsChoiceDialog(layer, parent)
            if not sd.exec_():
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                return

            fields = sd.selected_fields()
            if not fields:
                QMessageBox.information(self.iface.mainWindow(), "Data Properties", "No numeric fields selected.")
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                return
            opts = sd.requested_stats()

            # ROI-aware request
            req = QgsFeatureRequest()
            if rect is not None and layer.geometryType() != QgsWkbTypes.NullGeometry:
                canvas_crs = self.iface.mapCanvas().mapSettings().destinationCrs()
                if layer.crs() != canvas_crs:
                    xform = QgsCoordinateTransform(canvas_crs, layer.crs(), QgsProject.instance())
                    rect = xform.transform(rect)
                req.setFilterRect(rect)

            attr_idx = [layer.fields().indexFromName(f) for f in fields if layer.fields().indexFromName(f) != -1]

            if rect is None and layer.selectedFeatureIds():
                req_sel = QgsFeatureRequest(layer.selectedFeatureIds())
                if attr_idx:
                    req_sel.setSubsetOfAttributes(attr_idx)
                req_sel.setFlags(QgsFeatureRequest.NoGeometry)
                feats = list(layer.getFeatures(req_sel))
            else:
                if attr_idx:
                    req.setSubsetOfAttributes(attr_idx)
                req.setFlags(QgsFeatureRequest.NoGeometry)
                feats = list(layer.getFeatures(req))

            if not feats:
                QMessageBox.information(self.iface.mainWindow(), "Data Properties", "No features in the selected area.")
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                return

            # Compute stats and prep plot data
            stats_per_field = []
            plot_data = []   

            for fname in fields:
                idx = layer.fields().indexFromName(fname)
                if idx == -1:
                    continue

                vals = []
                for ft in feats:
                    v = ft[idx]
                    if v is None:
                        continue
                    try:
                        vals.append(float(v))
                    except Exception:
                        pass
                if not vals:
                    continue

                ss = QgsStatisticalSummary()
                ss.calculate(vals)

                stats_per_field.append(dict(
                    name=fname,
                    count=len(vals),
                    mean=ss.statistic(QgsStatisticalSummary.Mean),
                    median=ss.statistic(QgsStatisticalSummary.Median),
                    std=ss.statistic(QgsStatisticalSummary.StDev),
                    min=ss.statistic(QgsStatisticalSummary.Min),
                    max=ss.statistic(QgsStatisticalSummary.Max),
                ))

                if opts["histogram"]:
                    plot_data.append((fname, vals, int(opts["bins"])))

            if not stats_per_field and not plot_data:
                QMessageBox.information(self.iface.mainWindow(), "Data Properties", "No numeric results to show.")
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                return


            def fmt(x):
                try:
                    return f"{x:.6g}"
                except Exception:
                    return str(x)

            order  = ["count", "mean", "median", "std", "min", "max"]
            labels = {"count": "Count", "mean": "Mean", "median": "Median",
                    "std": "Std. Dev.", "min": "Min", "max": "Max"}
            vals_map = {}
            for fname, vals, bins_used in plot_data:
                vals_map[fname] = (vals, bins_used)

            sections = []
            for s in stats_per_field:
                fname = s["name"]
                html = [
                    "<style>table{border-collapse:collapse;} th,td{border:1px solid #ccc;padding:6px 10px;} th{background:#f5f5f5;text-align:left;}</style>",
                    f"<div class='field-title' style='font-weight:600;font-size:13pt;margin:0 0 6px 0'>{fname}</div>",
                    "<table><tbody>"
                ]
                for k in order:
                    html.append(f"<tr><th>{labels[k]}</th><td>{fmt(s[k])}</td></tr>")
                html.append("</tbody></table>")
                html = "".join(html)

                vals, bins_used = vals_map.get(fname, ([], int(opts["bins"])))
                sections.append({"name": fname, "html": html, "vals": vals, "bins": bins_used})

            if not sections:
                QMessageBox.information(self.iface.mainWindow(), "Data Properties", "No numeric results to show.")
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                return

            dlg2 = DataPropsResultsDialog(parent, "Data Properties (Summary)", sections)
            dlg2.resize(1100, 700)
            dlg2.exec_()

            QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))

        if roi_needed:
            canvas = self.iface.mapCanvas()
            self._rectTool = RectangleMapTool(canvas)
            self._prevTool = canvas.mapTool()

            def _finish(rect):
                QTimer.singleShot(0, lambda: self._restore_canvas_tool(force_pan=True))
                proceed_with_rect(rect)

            self._rectTool.rectangleSelected.connect(_finish)
            canvas.setMapTool(self._rectTool)
            self.iface.messageBar().pushInfo("Data Properties", "Draw a rectangle to select the area.")
        else:
            proceed_with_rect(None)